//! Host-side C# mirror codegen.
//!
//! # Responsibilities
//!
//! - Generate `generated/<module>_Components.g.cs` inside each optional module
//!   that exposes components to managed code, from the module's real
//!   registered layout (name, size, alignment).
//! - Keep the declaration with the module: nothing is hand-written in the
//!   C# project, and the generated file's content derives entirely from what
//!   the Rust module itself registered.
//!
//! # Design
//!
//! The generated struct is a raw ABI blob: `[StructLayout(LayoutKind.Sequential,
//! Size = N)]` plus a private alignment-driving pad field (C# struct alignment
//! is driven by fields, so the pad makes the managed alignment match the
//! module's registered layout). The `Raw` span property exposes the live bytes
//! in safe code, so typed C# can read/write the component through
//! `MemoryMarshal`. The host validates the generated struct's size/alignment
//! against the module binding when the managed manifest is registered, so a
//! generator bug cannot silently produce a mismatched mirror.
//!
//! The file is regenerated on every host startup. A committed copy is kept as
//! a bootstrap so standalone C# builds (IDE, `dotnet build`, the C# runtime
//! regression tests) compile without a prior host run; the host overwrites it
//! with identical content, so a matching module leaves the tree clean.

// Standard library
use std::path::Path;

// Current crate
use super::components::ModuleExposedComponent;

// =============================================================================
// Free Functions
// =============================================================================

/// C# primitive whose alignment drives the generated struct's alignment.
///
/// A struct with no fields defaults to 1-byte alignment in C# regardless of
/// `Size`, so a single private pad field of a matching-alignment primitive is
/// emitted to make `Marshal.OffsetOf`-style alignment probes agree with the
/// module's registered layout.
fn alignment_primitive(align: usize) -> Option<&'static str> {
    match align {
        1 => Some("byte"),
        2 => Some("ushort"),
        4 => Some("uint"),
        8 => Some("ulong"),
        _ => None,
    }
}

/// Split a derived C#-facing name (`pill_spline.Spline`) into its namespace and
/// type-name halves.
fn split_csharp_name(csharp_name: &str) -> Option<(&str, &str)> {
    let dot = csharp_name.rfind('.')?;
    Some((&csharp_name[..dot], &csharp_name[dot + 1..]))
}

/// Generate `<module>_Components.g.cs` inside the optional module's `generated`
/// directory for every component the module exposed to managed code.
///
/// # Errors
///
/// Returns a message when an exposed component has an unsupported alignment or
/// the generated file cannot be written.
pub(crate) fn generate_module_components_csharp(
    workspace_root: &Path,
    module_name: &str,
    exposed: &[ModuleExposedComponent],
) -> Result<(), String> {
    let module_root = workspace_root.join("optional").join(module_name);
    let generated_dir = module_root.join("generated");
    let output_path = generated_dir.join(format!("{module_name}_Components.g.cs"));

    // A module that exposes no components needs no mirror file. Remove a stale
    // file from an earlier generation so a component that stopped being
    // exposed cannot linger in the C# project (it would otherwise compile in a
    // struct whose binding no longer exists).
    if exposed.is_empty() {
        if output_path.exists() {
            std::fs::remove_file(&output_path).map_err(|error| {
                format!("cannot remove stale {}: {error}", output_path.display())
            })?;
        }
        return Ok(());
    }

    std::fs::create_dir_all(&generated_dir)
        .map_err(|error| format!("cannot create {}: {error}", generated_dir.display()))?;

    let mut content = String::new();
    content.push_str(
        "// AUTO-GENERATED by the Rust host from this optional module's component metadata.\n\
         // Do not edit: derived from the components the module itself registered.\n\
         // Regenerated on every host startup into generated/<module>_Components.g.cs.\n\
         using System;\n\
         using System.Runtime.CompilerServices;\n\
         using System.Runtime.InteropServices;\n\n",
    );

    for component in exposed {
        let (namespace, name) = split_csharp_name(&component.csharp_name).ok_or_else(|| {
            format!(
                "derived C# name {} has no namespace separator",
                component.csharp_name
            )
        })?;
        let align_primitive = alignment_primitive(component.align).ok_or_else(|| {
            format!(
                "unsupported alignment {} for exposed component {}",
                component.align, component.csharp_name
            )
        })?;

        content.push_str(&format!(
            "namespace {namespace} {{\n\
             \n\
             [StructLayout(LayoutKind.Sequential, Size = {size})]\n\
             public struct {name}\n\
             {{\n\
             \x20\x20\x20\x20/// {size}-byte, {align}-byte-aligned ABI mirror of a component\n\
             \x20\x20\x20\x20/// registered by this optional Rust module.\n\
             \x20\x20\x20\x20private readonly {align_primitive} _alignmentPad;\n\
             \n\
             \x20\x20\x20\x20/// Live ABI bytes of this component row (safe code).\n\
             \x20\x20\x20\x20public readonly Span<byte> Raw =>\n\
             \x20\x20\x20\x20\x20\x20\x20\x20MemoryMarshal.AsBytes(MemoryMarshal.CreateSpan(ref Unsafe.AsRef(in this), 1));\n\
             }}\n\
             \n\
             }}\n\
             \n",
            namespace = namespace,
            name = name,
            size = component.size,
            align = component.align,
            align_primitive = align_primitive,
        ));
    }

    // Write only when the file is missing or its content differs from what
    // this startup would generate. The generated file depends on the module's
    // registered layout (name/size/align), so "up to date" is a content
    // comparison, not a timestamp comparison: a module rebuild that does not
    // change the layout leaves the file and its mtime untouched (keeping the
    // committed bootstrap clean), while a layout change (or a missing file)
    // triggers a rewrite.
    match std::fs::read(&output_path) {
        // Up to date: identical content leaves the file and its mtime alone.
        Ok(existing) if existing == content.as_bytes() => return Ok(()),
        // Missing or different: fall through to rewrite.
        _ => {}
    }

    std::fs::write(&output_path, content)
        .map_err(|error| format!("cannot write {}: {error}", output_path.display()))?;
    Ok(())
}

// =============================================================================
// Tests
// =============================================================================

/// Regression tests for the host-side C# mirror generation.
///
/// Each test drives [`generate_module_components_csharp`] against a fresh temp
/// workspace shaped like the real repo (`<root>/optional/<module>/generated/`),
/// covering: generated content, the alignment-pad matrix, namespace splitting,
/// the up-to-date / missing / stale rewrite conditions, per-module file
/// isolation, stale-file removal when a module stops exposing components,
/// determinism, and the error paths.
#[cfg(test)]
mod tests {
    use super::*;
    use pill_engine::ComponentId;
    use std::path::{Path, PathBuf};

    /// Create a fresh temp workspace and the module directory under it.
    fn temp_workspace(test_name: &str, module_name: &str) -> PathBuf {
        let root =
            std::env::temp_dir().join(format!("pill_codegen_{}_{}", test_name, std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(root.join("optional").join(module_name))
            .expect("create temp module dir");
        root
    }

    /// One exposed component with a synthetic stable identity.
    fn exposed(name: &str, size: usize, align: usize) -> ModuleExposedComponent {
        ModuleExposedComponent {
            csharp_name: name.to_string(),
            component_id: ComponentId::dynamic(0xABCD_0001_0000_0001),
            size,
            align,
        }
    }

    fn generated_path(workspace: &Path, module_name: &str) -> PathBuf {
        workspace
            .join("optional")
            .join(module_name)
            .join("generated")
            .join(format!("{module_name}_Components.g.cs"))
    }

    fn read_generated(workspace: &Path, module_name: &str) -> String {
        std::fs::read_to_string(generated_path(workspace, module_name))
            .expect("generated file is readable")
    }

    /// The generated mirror must sit inside the optional module's own
    /// `generated` directory, not in the C# project.
    #[test]
    fn generated_file_lives_inside_the_module_directory() {
        let workspace = temp_workspace("location", "pill_spline");
        generate_module_components_csharp(
            &workspace,
            "pill_spline",
            &[exposed("pill_spline.Spline", 196, 4)],
        )
        .unwrap();
        assert!(generated_path(&workspace, "pill_spline").exists());
        assert!(generated_path(&workspace, "pill_spline")
            .starts_with(workspace.join("optional").join("pill_spline")));
    }

    /// A single component produces a struct with the right namespace, name,
    /// size, alignment pad, and the safe raw-bytes accessor.
    #[test]
    fn generates_mirror_for_a_single_component() {
        let workspace = temp_workspace("single", "pill_spline");
        generate_module_components_csharp(
            &workspace,
            "pill_spline",
            &[exposed("pill_spline.Spline", 196, 4)],
        )
        .unwrap();

        let content = read_generated(&workspace, "pill_spline");
        assert!(content.contains("namespace pill_spline {"));
        assert!(content.contains("public struct Spline"));
        assert!(content.contains("Size = 196"));
        assert!(content.contains("private readonly uint _alignmentPad;"));
        assert!(content.contains("public readonly Span<byte> Raw =>"));
        assert!(content.contains("MemoryMarshal.CreateSpan(ref Unsafe.AsRef(in this), 1)"));
    }

    /// Multiple components from the same module land in one file, each in its
    /// own namespace, with per-component size and alignment.
    #[test]
    fn generates_multiple_components_in_multiple_namespaces() {
        let workspace = temp_workspace("multi", "pill_spline");
        let components = [
            exposed("pill_spline.Spline", 196, 4),
            exposed("pill_spline.Path", 12, 4),
            exposed("tracy_nav.Segment", 16, 8),
        ];
        generate_module_components_csharp(&workspace, "pill_spline", &components).unwrap();

        let content = read_generated(&workspace, "pill_spline");
        assert!(content.contains("namespace pill_spline {"));
        assert!(content.contains("namespace tracy_nav {"));
        assert!(content.contains("public struct Spline"));
        assert!(content.contains("public struct Path"));
        assert!(content.contains("public struct Segment"));
        assert!(content.contains("Size = 196"));
        assert!(content.contains("Size = 12"));
        assert!(content.contains("Size = 16"));
        // align 8 uses a ulong pad.
        assert!(content.contains("private readonly ulong _alignmentPad;"));
    }

    /// The alignment pad primitive must match each supported alignment, since
    /// C# struct alignment is driven by fields.
    #[test]
    fn alignment_pad_matches_each_supported_alignment() {
        for (align, expected_pad) in [
            (1usize, "byte"),
            (2usize, "ushort"),
            (4usize, "uint"),
            (8usize, "ulong"),
        ] {
            let workspace = temp_workspace(&format!("align_{align}"), "pill_spline");
            generate_module_components_csharp(
                &workspace,
                "pill_spline",
                &[exposed("pill_spline.Spline", 16, align)],
            )
            .unwrap();
            let content = read_generated(&workspace, "pill_spline");
            assert!(
                content.contains(&format!("private readonly {expected_pad} _alignmentPad;")),
                "alignment {align} must use a {expected_pad} pad field"
            );
        }
    }

    /// An alignment with no C# primitive is rejected and writes nothing.
    #[test]
    fn unsupported_alignment_is_rejected() {
        let workspace = temp_workspace("bad_align", "pill_spline");
        let result = generate_module_components_csharp(
            &workspace,
            "pill_spline",
            &[exposed("pill_spline.Spline", 16, 3)],
        );
        let error = result.expect_err("alignment 3 is unsupported");
        assert!(error.contains("unsupported alignment"));
        assert!(
            !generated_path(&workspace, "pill_spline").exists(),
            "a rejected generation must not write a file"
        );
    }

    /// A derived C# name without a namespace separator is rejected.
    #[test]
    fn name_without_namespace_is_rejected() {
        let workspace = temp_workspace("no_namespace", "pill_spline");
        let result = generate_module_components_csharp(
            &workspace,
            "pill_spline",
            &[exposed("Spline", 4, 4)],
        );
        let error = result.expect_err("a name without '.' cannot be namespaced");
        assert!(error.contains("no namespace separator"));
    }

    /// Regenerating with identical content must not touch the file (mtime
    /// preserved), which keeps the committed bootstrap clean.
    #[test]
    fn skips_rewrite_when_content_is_identical() {
        let workspace = temp_workspace("up_to_date", "pill_spline");
        let components = [exposed("pill_spline.Spline", 196, 4)];
        generate_module_components_csharp(&workspace, "pill_spline", &components).unwrap();

        let before = std::fs::metadata(generated_path(&workspace, "pill_spline"))
            .unwrap()
            .modified()
            .unwrap();
        generate_module_components_csharp(&workspace, "pill_spline", &components).unwrap();
        let after = std::fs::metadata(generated_path(&workspace, "pill_spline"))
            .unwrap()
            .modified()
            .unwrap();
        assert_eq!(
            before, after,
            "identical content must not rewrite the generated file"
        );
    }

    /// A missing file is regenerated.
    #[test]
    fn writes_when_file_is_missing() {
        let workspace = temp_workspace("missing", "pill_spline");
        let components = [exposed("pill_spline.Spline", 196, 4)];
        generate_module_components_csharp(&workspace, "pill_spline", &components).unwrap();
        std::fs::remove_file(generated_path(&workspace, "pill_spline")).unwrap();

        generate_module_components_csharp(&workspace, "pill_spline", &components).unwrap();
        assert!(generated_path(&workspace, "pill_spline").exists());
    }

    /// A layout change (size/align) triggers a rewrite with the new values.
    #[test]
    fn rewrites_when_layout_changed() {
        let workspace = temp_workspace("layout_changed", "pill_spline");
        generate_module_components_csharp(
            &workspace,
            "pill_spline",
            &[exposed("pill_spline.Spline", 196, 4)],
        )
        .unwrap();
        assert!(read_generated(&workspace, "pill_spline").contains("Size = 196"));

        generate_module_components_csharp(
            &workspace,
            "pill_spline",
            &[exposed("pill_spline.Spline", 200, 8)],
        )
        .unwrap();
        let content = read_generated(&workspace, "pill_spline");
        assert!(content.contains("Size = 200"));
        assert!(content.contains("private readonly ulong _alignmentPad;"));
    }

    /// Different modules write separate files, and one module's mirror never
    /// leaks into another's.
    #[test]
    fn writes_separate_files_per_module() {
        let workspace = temp_workspace("per_module", "pill_spline");
        std::fs::create_dir_all(workspace.join("optional").join("other_module")).unwrap();
        generate_module_components_csharp(
            &workspace,
            "pill_spline",
            &[exposed("pill_spline.Spline", 196, 4)],
        )
        .unwrap();
        generate_module_components_csharp(
            &workspace,
            "other_module",
            &[exposed("other_module.Gadget", 8, 4)],
        )
        .unwrap();

        let spline_file = read_generated(&workspace, "pill_spline");
        let gadget_file = read_generated(&workspace, "other_module");
        assert!(spline_file.contains("Spline"));
        assert!(!spline_file.contains("Gadget"));
        assert!(gadget_file.contains("Gadget"));
        assert!(!gadget_file.contains("Spline"));
    }

    /// A module that stops exposing components removes its stale mirror file
    /// so a vanished binding cannot linger in the C# project.
    #[test]
    fn empty_exposure_removes_stale_file() {
        let workspace = temp_workspace("emptied", "pill_spline");
        generate_module_components_csharp(
            &workspace,
            "pill_spline",
            &[exposed("pill_spline.Spline", 196, 4)],
        )
        .unwrap();
        assert!(generated_path(&workspace, "pill_spline").exists());

        generate_module_components_csharp(&workspace, "pill_spline", &[]).unwrap();
        assert!(
            !generated_path(&workspace, "pill_spline").exists(),
            "a module exposing nothing must not keep a stale mirror"
        );
    }

    /// The same input produces byte-identical output on fresh workspaces, so
    /// regeneration never dirties the committed bootstrap.
    #[test]
    fn output_is_deterministic() {
        let first = temp_workspace("deterministic_a", "pill_spline");
        let second = temp_workspace("deterministic_b", "pill_spline");
        let components = [
            exposed("pill_spline.Spline", 196, 4),
            exposed("pill_spline.Path", 12, 4),
        ];
        generate_module_components_csharp(&first, "pill_spline", &components).unwrap();
        generate_module_components_csharp(&second, "pill_spline", &components).unwrap();

        assert_eq!(
            read_generated(&first, "pill_spline"),
            read_generated(&second, "pill_spline")
        );
    }
}
