//! Host-side C# mirror codegen.
//!
//! # Responsibilities
//!
//! - Generate `generated/<module>_Components.g.cs` inside each optional module
//!   that exposes components to managed code, from the module's real
//!   registered layout (name, size, alignment).
//! - Keep the declaration with the module: nothing is hand-written in the
//!   C# project, and the generated file's content derives entirely from what
//!   the Rust module itself registered.
//!
//! # Design
//!
//! The generated struct is a raw ABI blob: `[StructLayout(LayoutKind.Sequential,
//! Size = N)]` plus a private alignment-driving pad field (C# struct alignment
//! is driven by fields, so the pad makes the managed alignment match the
//! module's registered layout). The `Raw` span property exposes the live bytes
//! in safe code, so typed C# can read/write the component through
//! `MemoryMarshal`. The host validates the generated struct's size/alignment
//! against the module binding when the managed manifest is registered, so a
//! generator bug cannot silently produce a mismatched mirror.
//!
//! The file is regenerated on every host startup. A committed copy is kept as
//! a bootstrap so standalone C# builds (IDE, `dotnet build`, the C# runtime
//! regression tests) compile without a prior host run; the host overwrites it
//! with identical content, so a matching module leaves the tree clean.

// Standard library
use std::path::Path;

// External crates
use pill_engine::component_registry::{ComponentFieldDescriptor, PillValueTypeDescriptor};

// Current crate
use super::components::ModuleExposedComponent;
use super::ResolvedMirrorMethod;

// =============================================================================
// Free Functions
// =============================================================================

/// C# primitive whose alignment drives the generated struct's alignment.
///
/// A struct with no fields defaults to 1-byte alignment in C# regardless of
/// `Size`, so a single private pad field of a matching-alignment primitive is
/// emitted to make `Marshal.OffsetOf`-style alignment probes agree with the
/// module's registered layout.
fn alignment_primitive(align: usize) -> Option<&'static str> {
    match align {
        1 => Some("byte"),
        2 => Some("ushort"),
        4 => Some("uint"),
        8 => Some("ulong"),
        _ => None,
    }
}

/// Split a derived C#-facing name (`pill_spline.Spline`) into its namespace and
/// type-name halves.
fn split_csharp_name(csharp_name: &str) -> Option<(&str, &str)> {
    let dot = csharp_name.rfind('.')?;
    Some((&csharp_name[..dot], &csharp_name[dot + 1..]))
}

/// Generate `<module>_Components.g.cs` inside the optional module's `generated`
/// directory for every component the module exposed to managed code.
///
/// Returns `Ok(true)` when the mirror file was written or removed, and
/// `Ok(false)` when the existing file already matched what this call would
/// generate. The change flag lets the reload path queue a C# project rebuild
/// only when the module's mirror surface actually moved.
///
/// # Errors
///
/// Returns a message when an exposed component has an unsupported alignment or
/// the generated file cannot be written.
pub(crate) fn generate_module_components_csharp(
    workspace_root: &Path,
    module_name: &str,
    exposed: &[ModuleExposedComponent],
    value_types: &[PillValueTypeDescriptor],
    methods: &[ResolvedMirrorMethod],
) -> Result<bool, String> {
    let module_root = workspace_root.join("optional").join(module_name);
    let generated_dir = module_root.join("generated");
    let output_path = generated_dir.join(format!("{module_name}_Components.g.cs"));

    // A module that exposes no components needs no mirror file. Remove a stale
    // file from an earlier generation so a component that stopped being
    // exposed cannot linger in the C# project (it would otherwise compile in a
    // struct whose binding no longer exists).
    if exposed.is_empty() {
        if output_path.exists() {
            std::fs::remove_file(&output_path).map_err(|error| {
                format!("cannot remove stale {}: {error}", output_path.display())
            })?;
            return Ok(true);
        }
        return Ok(false);
    }

    std::fs::create_dir_all(&generated_dir)
        .map_err(|error| format!("cannot create {}: {error}", generated_dir.display()))?;

    let mut content = String::new();
    content.push_str(
        "// AUTO-GENERATED by the Rust host from this optional module's component metadata.\n\
         // Do not edit: derived from the components the module itself registered.\n\
         // Regenerated on every host startup into generated/<module>_Components.g.cs.\n\
         // Components registered with compile-time field layouts are emitted as\n\
         // typed structs; everything else is an opaque ABI blob with a `Raw` span.\n\
         using System;\n\
         using System.Runtime.CompilerServices;\n\
         using System.Runtime.InteropServices;\n\n",
    );

    // Nested `#[derive(PillMirror)]` struct definitions, deduplicated by Rust
    // qualified path and pushed in dependency order, so concatenating them in
    // order always compiles. Emitted once per file, before the components.
    let mut nested_definitions: Vec<EmittedStruct> = Vec::new();
    let mut component_blocks: Vec<(String, String)> = Vec::new();

    for component in exposed {
        let (namespace, name) = split_csharp_name(&component.csharp_name).ok_or_else(|| {
            format!(
                "derived C# name {} has no namespace separator",
                component.csharp_name
            )
        })?;
        // Components registered with the derive carry a typed field layout;
        // everything else keeps the opaque ABI blob.
        let body = if component.fields.is_empty() {
            emit_blob_component(name, component.size, component.align)?
        } else {
            emit_typed_struct(
                name,
                &component.fields,
                component.size,
                component.align,
                value_types,
                &mut nested_definitions,
                methods,
                "",
            )?
        };
        component_blocks.push((namespace.to_string(), body));
    }

    // Mirror every plain value type the module declared, not just the ones a
    // component referenced, so `#[derive(PillMirror)]` on its own is enough to
    // expose a type to C#. Referenced types are already in `nested_definitions`
    // and are skipped here.
    for value_type in value_types {
        if nested_definitions
            .iter()
            .any(|entry| entry.qualified == value_type.type_name)
        {
            continue;
        }
        let cs_name = last_path_segment(value_type.type_name);
        if let Some(existing) = nested_definitions
            .iter()
            .find(|entry| last_path_segment(&entry.qualified) == cs_name)
        {
            return Err(format!(
                "value types `{}` and `{}` both map to C# name `{cs_name}`",
                existing.qualified, value_type.type_name
            ));
        }
        let definition = emit_typed_struct(
            &cs_name,
            value_type.fields,
            value_type.size,
            value_type.align,
            value_types,
            &mut nested_definitions,
            methods,
            value_type.type_name,
        )?;
        nested_definitions.push(EmittedStruct {
            qualified: value_type.type_name.to_string(),
            definition,
        });
    }

    // Nested value types live in the same namespace as the components that
    // reference them, so C# refers to `pill_spline.Vector3f` etc.
    for nested in &nested_definitions {
        let namespace = component_blocks
            .first()
            .map(|(namespace, _)| namespace.clone())
            .unwrap_or_else(|| format!("pill_{module_name}"));
        content.push_str(&format!(
            "namespace {namespace} {{\n\n{}\n\n}}\n\n",
            nested.definition
        ));
    }
    for (namespace, body) in component_blocks {
        content.push_str(&format!("namespace {namespace} {{\n\n{body}\n\n}}\n\n"));
    }

    // Write only when the file is missing or its content differs from what
    // this startup would generate. The generated file depends on the module's
    // registered layout (name/size/align/fields), so "up to date" is a content
    // comparison, not a timestamp comparison: a module rebuild that does not
    // change the layout leaves the file and its mtime untouched (keeping the
    // committed bootstrap clean), while a layout change (or a missing file)
    // triggers a rewrite.
    match std::fs::read(&output_path) {
        // Up to date: identical content leaves the file and its mtime alone.
        Ok(existing) if existing == content.as_bytes() => return Ok(false),
        // Missing or different: fall through to rewrite.
        _ => {}
    }

    std::fs::write(&output_path, content)
        .map_err(|error| format!("cannot write {}: {error}", output_path.display()))?;
    Ok(true)
}

/// One nested C# struct definition to emit, deduplicated by Rust path.
struct EmittedStruct {
    /// Rust qualified path the definition was generated from.
    qualified: String,
    /// Full C# struct text (without the namespace wrapper).
    definition: String,
}

/// Emit the opaque ABI-blob mirror for a component with no field metadata.
fn emit_blob_component(name: &str, size: usize, align: usize) -> Result<String, String> {
    let align_primitive = alignment_primitive(align)
        .ok_or_else(|| format!("unsupported alignment {align} for exposed component {name}"))?;
    Ok(format!(
        "[StructLayout(LayoutKind.Sequential, Size = {size})]\n\
         public struct {name}\n\
         {{\n\
         \x20\x20\x20\x20/// {size}-byte, {align}-byte-aligned ABI mirror of a component\n\
         \x20\x20\x20\x20/// registered by this optional Rust module.\n\
         \x20\x20\x20\x20private readonly {align_primitive} _alignmentPad;\n\
         \n\
         \x20\x20\x20\x20/// Live ABI bytes of this component row (safe code).\n\
         \x20\x20\x20\x20public readonly Span<byte> Raw =>\n\
         \x20\x20\x20\x20\x20\x20\x20\x20MemoryMarshal.AsBytes(MemoryMarshal.CreateSpan(ref Unsafe.AsRef(in this), 1));\n\
         }}\n",
        size = size,
        align = align,
        align_primitive = align_primitive,
    ))
}

/// Emit one typed C# struct from a compile-time field layout.
///
/// `size`/`align` come from the Rust type; alignment above 8 is rejected
/// because no C# primitive can drive it. `struct:` fields are resolved against
/// the module's `PillMirror` inventory (recursively), falling back to an
/// opaque blob of the field's size when a type is not declared. Nested
/// definitions are appended to `emitted` in dependency order.
/// Emit a typed C# struct from a compile-time field layout.
///
/// The many parameters mirror the descriptor fields plus the recursion
/// context; clippy's threshold is below the (internal) signature's size.
#[allow(clippy::too_many_arguments)]
fn emit_typed_struct(
    name: &str,
    fields: &[ComponentFieldDescriptor],
    size: usize,
    align: usize,
    value_types: &[PillValueTypeDescriptor],
    emitted: &mut Vec<EmittedStruct>,
    methods: &[ResolvedMirrorMethod],
    qualified: &str,
) -> Result<String, String> {
    if align > 8 {
        return Err(format!(
            "type `{name}` has alignment {align} > 8; C# mirrors cannot express over-aligned layouts"
        ));
    }

    // Step 1: validate the descriptor and resolve every field to concrete C#
    // declarations with byte offsets and element sizes.
    let mut resolved: Vec<(String, String, usize, usize)> = Vec::new();
    let mut sorted: Vec<&ComponentFieldDescriptor> = fields.iter().collect();
    sorted.sort_by_key(|field| field.offset);
    for field in &sorted {
        if field.size == 0 || field.offset + field.size > size {
            return Err(format!(
                "field `{}` of `{name}` spans bytes {}..{} outside the {size}-byte type",
                field.name,
                field.offset,
                field.offset + field.size
            ));
        }
        let (base_tag, is_array) = split_array_tag(field.type_tag)?;
        let (element_size, element_align) = if is_array {
            if field.element_count == 0 {
                return Err(format!(
                    "array field `{}` of `{name}` reports zero elements",
                    field.name
                ));
            }
            if field.size % field.element_count != 0 {
                return Err(format!(
                    "array field `{}` of `{name}` has size {} not divisible by {} elements",
                    field.name, field.size, field.element_count
                ));
            }
            (field.size / field.element_count, field.align)
        } else {
            (field.size, field.align)
        };
        if element_align > 8 {
            return Err(format!(
                "field `{}` of `{name}` has element alignment {element_align} > 8; not expressible in a C# mirror",
                field.name
            ));
        }
        let cs_type = if let Some((cs, _, _)) = cs_primitive(base_tag) {
            cs.to_string()
        } else if let Some(qualified) = base_tag.strip_prefix("struct:") {
            emit_nested_struct(
                qualified,
                element_size,
                element_align,
                value_types,
                emitted,
                methods,
            )?
        } else {
            return Err(format!(
                "unsupported type tag `{}` for field `{}` of `{name}`",
                field.type_tag, field.name
            ));
        };
        let pascal = snake_to_pascal(field.name);
        if is_array {
            for index in 0..field.element_count {
                let offset = field.offset + index * element_size;
                resolved.push((
                    format!("{pascal}{index}"),
                    cs_type.clone(),
                    offset,
                    element_size,
                ));
            }
        } else {
            resolved.push((pascal, cs_type, field.offset, element_size));
        }
    }

    // Step 2: siblings must not overlap - two C# fields over one byte range
    // would be a silent data race on the same storage.
    resolved.sort_by_key(|(_, _, offset, _)| *offset);
    for pair in resolved.windows(2) {
        let (_, _, left_offset, left_size) = &pair[0];
        let (_, _, right_offset, _) = &pair[1];
        if *left_offset + *left_size > *right_offset {
            return Err(format!(
                "fields of `{name}` overlap at byte {}; the derive produced an invalid layout",
                right_offset
            ));
        }
    }

    // Step 3: emit the struct. `Size` forces the exact Rust byte size even
    // when trailing padding exists; `Raw` keeps the live-bytes escape hatch.
    let mut body = String::new();
    body.push_str(&format!(
        "[StructLayout(LayoutKind.Explicit, Size = {size})]\npublic struct {name}\n{{\n"
    ));
    for (cs_field, cs_type, offset, _) in &resolved {
        body.push_str(&format!(
            "    [FieldOffset({offset})] public {cs_type} {cs_field};\n"
        ));
    }
    body.push_str(
        "    /// Live ABI bytes of this component row (safe code).\n\
         \x20\x20\x20\x20public readonly Span<byte> Raw =>\n\
         \x20\x20\x20\x20\x20\x20\x20\x20MemoryMarshal.AsBytes(MemoryMarshal.CreateSpan(ref Unsafe.AsRef(in this), 1));\n",
    );
    // Mirrored methods (from `#[pill_mirror_impl]`) become typed C# instance
    // methods that call the Rust implementation through its C-ABI trampoline.
    if !qualified.is_empty() {
        body.push_str(&emit_value_type_methods(name, qualified, methods)?);
    }
    body.push_str("}\n");
    Ok(body)
}

/// Emit (once) the typed C# struct for a `struct:<path>` field tag.
///
/// Resolves the path against the module's `PillMirror` inventory; when the
/// type is declared, its own field layout is emitted recursively. When it is
/// not (an enum, a plain struct that never derived `PillMirror`, a foreign
/// type), an opaque blob of the field's element size/alignment is emitted so
/// the mirror still compiles and stays size-correct.
fn emit_nested_struct(
    qualified: &str,
    size: usize,
    align: usize,
    value_types: &[PillValueTypeDescriptor],
    emitted: &mut Vec<EmittedStruct>,
    methods: &[ResolvedMirrorMethod],
) -> Result<String, String> {
    let cs_name = last_path_segment(qualified);
    if let Some(existing) = emitted.iter().find(|entry| entry.qualified == qualified) {
        // Already emitted for an earlier field; reuse the same C# name.
        return Ok(last_path_segment(&existing.qualified));
    }
    if let Some(existing) = emitted
        .iter()
        .find(|entry| last_path_segment(&entry.qualified) == cs_name)
    {
        return Err(format!(
            "nested value types `{}` and `{}` both map to C# name `{cs_name}`; rename one",
            existing.qualified, qualified
        ));
    }
    let definition = match value_types
        .iter()
        .find(|descriptor| descriptor.type_name == qualified)
    {
        Some(descriptor) => {
            if descriptor.size != size || descriptor.align != align {
                return Err(format!(
                    "value type `{qualified}` is {}-byte/{}-aligned but the field using it is {size}-byte/{align}-aligned; rebuild the module so the mirror matches",
                    descriptor.size, descriptor.align
                ));
            }
            emit_typed_struct(
                &cs_name,
                descriptor.fields,
                descriptor.size,
                descriptor.align,
                value_types,
                emitted,
                methods,
                descriptor.type_name,
            )?
        }
        None => emit_opaque_struct(&cs_name, size, align)?,
    };
    emitted.push(EmittedStruct {
        qualified: qualified.to_string(),
        definition,
    });
    Ok(cs_name)
}

/// Emit an opaque blob struct for a nested type with no `PillMirror` descriptor.
fn emit_opaque_struct(name: &str, size: usize, align: usize) -> Result<String, String> {
    let align_primitive = alignment_primitive(align)
        .ok_or_else(|| format!("unsupported alignment {align} for nested value type `{name}`"))?;
    Ok(format!(
        "[StructLayout(LayoutKind.Sequential, Size = {size})]\n\
         public struct {name}\n\
         {{\n\
         \x20\x20\x20\x20private readonly {align_primitive} _alignmentPad;\n\
         \n\
         \x20\x20\x20\x20/// Live ABI bytes of this value type; it was not declared with\n\
         \x20\x20\x20\x20/// `#[derive(PillMirror)]`, so its fields stay opaque.\n\
         \x20\x20\x20\x20public readonly Span<byte> Raw =>\n\
         \x20\x20\x20\x20\x20\x20\x20\x20MemoryMarshal.AsBytes(MemoryMarshal.CreateSpan(ref Unsafe.AsRef(in this), 1));\n\
         }}\n",
        size = size,
        align_primitive = align_primitive,
    ))
}

/// C# reserved keywords that cannot name a parameter.
///
/// A Rust argument may legally be named like any of these (`event`, `string`,
/// `ref`, ...) because Rust reserves a different set of words. Emitting it
/// verbatim would make the generated project fail to compile, so such an
/// argument falls back to a positional `argN` name (clearer in generated code
/// than `@`-escaping, and immune to future keyword additions).
const CSHARP_RESERVED_KEYWORDS: &[&str] = &[
    "abstract",
    "as",
    "base",
    "bool",
    "break",
    "byte",
    "case",
    "catch",
    "char",
    "checked",
    "class",
    "const",
    "continue",
    "decimal",
    "default",
    "delegate",
    "do",
    "double",
    "else",
    "enum",
    "event",
    "explicit",
    "extern",
    "false",
    "finally",
    "fixed",
    "float",
    "for",
    "foreach",
    "goto",
    "if",
    "implicit",
    "in",
    "int",
    "interface",
    "internal",
    "is",
    "lock",
    "long",
    "namespace",
    "new",
    "null",
    "object",
    "operator",
    "out",
    "override",
    "params",
    "private",
    "protected",
    "public",
    "readonly",
    "ref",
    "return",
    "sbyte",
    "sealed",
    "short",
    "sizeof",
    "stackalloc",
    "static",
    "string",
    "struct",
    "switch",
    "this",
    "throw",
    "true",
    "try",
    "typeof",
    "uint",
    "ulong",
    "unchecked",
    "unsafe",
    "ushort",
    "using",
    "virtual",
    "void",
    "volatile",
    "while",
];

/// The parameter name the generated C# uses for one mirrored-method argument.
///
/// Prefers the Rust parameter name captured by the macro; falls back to a
/// positional `argN` when the name is blank or is a C# reserved keyword.
fn csharp_parameter_name(argument_index: usize, rust_name: &str) -> String {
    if !rust_name.is_empty() && !CSHARP_RESERVED_KEYWORDS.contains(&rust_name) {
        rust_name.to_string()
    } else {
        format!("arg{argument_index}")
    }
}

/// Emit the typed C# instance methods that mirror a value type's
/// `#[pill_mirror_method]` Rust methods.
///
/// Each mirrored method becomes a `[UnmanagedFunctionPointer(Cdecl)]` delegate
/// (nested inside the struct) and an instance method that resolves the
/// module's exported trampoline through [`TracyLive.MirrorMethods`] and calls
/// it with the struct pinned. Everything stays safe C#: the reloadable
/// project assembly compiles without `AllowUnsafeBlocks`, so the receiver is
/// pinned through a `GCHandle` over a boxed copy rather than a raw pointer.
/// That is why only `&self` (read-only) methods are supported: writes through
/// `&mut self` could never propagate back to the caller's copy.
///
/// Returns an empty string when the value type has no mirrored methods.
fn emit_value_type_methods(
    cs_name: &str,
    qualified: &str,
    methods: &[ResolvedMirrorMethod],
) -> Result<String, String> {
    let matching: Vec<&ResolvedMirrorMethod> = methods
        .iter()
        .filter(|method| method.type_name == qualified)
        .collect();
    if matching.is_empty() {
        return Ok(String::new());
    }

    let mut output = String::new();
    for method in matching {
        let pascal = snake_to_pascal(&method.method_name);
        let return_type = if method.return_tag.is_empty() {
            "void".to_string()
        } else {
            cs_primitive(&method.return_tag)
                .map(|(cs, _, _)| cs.to_string())
                .ok_or_else(|| {
                    format!(
                        "mirrored method `{}.{}` has unsupported return tag `{}`",
                        qualified, method.method_name, method.return_tag
                    )
                })?
        };
        let mut arg_types: Vec<String> = Vec::new();
        let mut arg_names: Vec<String> = Vec::new();
        for (index, tag) in method.arg_tags.iter().enumerate() {
            let cs_type = cs_primitive(tag)
                .map(|(cs, _, _)| cs.to_string())
                .ok_or_else(|| {
                    format!(
                        "mirrored method `{}.{}` has unsupported argument tag `{}`",
                        qualified, method.method_name, tag
                    )
                })?;
            arg_types.push(cs_type);
            // The Rust parameter name is preserved so the mirror reads like the
            // original; a missing/blank name or a C# keyword (a Rust argument
            // may legally be named `event`) falls back to a positional `argN`.
            let rust_name = method.arg_names.get(index).map_or("", String::as_str);
            arg_names.push(csharp_parameter_name(index, rust_name));
        }

        let delegate_name = format!("{cs_name}{pascal}Delegate");
        let typed_arguments: Vec<String> = arg_types
            .iter()
            .zip(arg_names.iter())
            .map(|(cs_type, arg_name)| format!("{cs_type} {arg_name}"))
            .collect();
        let delegate_args = if typed_arguments.is_empty() {
            "IntPtr self".to_string()
        } else {
            format!("IntPtr self, {}", typed_arguments.join(", "))
        };
        let call_args = if arg_names.is_empty() {
            "handle.AddrOfPinnedObject()".to_string()
        } else {
            format!("handle.AddrOfPinnedObject(), {}", arg_names.join(", "))
        };
        let method_signature = if typed_arguments.is_empty() {
            format!("public {return_type} {pascal}()")
        } else {
            format!(
                "public {return_type} {pascal}({})",
                typed_arguments.join(", ")
            )
        };
        let invocation = if method.return_tag.is_empty() {
            format!("mirror({call_args});")
        } else {
            format!("return mirror({call_args});")
        };

        output.push_str(&format!(
            "\n\
             \x20\x20\x20\x20/// Calls the Rust method `{qualified}::{method_name}` through its\n\
             \x20\x20\x20\x20/// generated C-ABI trampoline; this struct is pinned for the call.\n\
             \x20\x20\x20\x20[UnmanagedFunctionPointer(CallingConvention.Cdecl)]\n\
             \x20\x20\x20\x20public delegate {return_type} {delegate_name}({delegate_args});\n\
             \n\
             \x20\x20\x20\x20{method_signature}\n\
             \x20\x20\x20\x20{{\n\
             \x20\x20\x20\x20\x20\x20\x20\x20var mirror = global::TracyLive.MirrorMethods.Resolve<{delegate_name}>(\"{qualified}\", \"{method_name}\");\n\
             \x20\x20\x20\x20\x20\x20\x20\x20object boxed = this;\n\
             \x20\x20\x20\x20\x20\x20\x20\x20var handle = global::System.Runtime.InteropServices.GCHandle.Alloc(boxed, global::System.Runtime.InteropServices.GCHandleType.Pinned);\n\
             \x20\x20\x20\x20\x20\x20\x20\x20try {{ {invocation} }}\n\
             \x20\x20\x20\x20\x20\x20\x20\x20finally {{ handle.Free(); }}\n\
             \x20\x20\x20\x20}}\n",
            qualified = qualified,
            method_name = method.method_name,
            return_type = return_type,
            delegate_name = delegate_name,
            delegate_args = delegate_args,
            method_signature = method_signature,
            invocation = invocation,
        ));
    }
    Ok(output)
}

/// Split an `array:<inner>` tag into its base tag and whether it is an array.
fn split_array_tag(tag: &str) -> Result<(&str, bool), String> {
    match tag.strip_prefix("array:") {
        Some(inner) => Ok((inner, true)),
        None => Ok((tag, false)),
    }
}

/// Map a primitive type tag to its C# type, byte size, and alignment.
fn cs_primitive(tag: &str) -> Option<(&'static str, usize, usize)> {
    match tag {
        "f32" => Some(("float", 4, 4)),
        "f64" => Some(("double", 8, 8)),
        "i8" => Some(("sbyte", 1, 1)),
        "u8" => Some(("byte", 1, 1)),
        "i16" => Some(("short", 2, 2)),
        "u16" => Some(("ushort", 2, 2)),
        "i32" => Some(("int", 4, 4)),
        "u32" => Some(("uint", 4, 4)),
        "i64" => Some(("long", 8, 8)),
        "u64" => Some(("ulong", 8, 8)),
        // Rust `bool` is one byte; C# `bool` is marshal-ambiguous, so the
        // mirror exposes the raw byte.
        "bool" => Some(("byte", 1, 1)),
        "usize" => Some((
            "UIntPtr",
            std::mem::size_of::<usize>(),
            std::mem::align_of::<usize>(),
        )),
        "isize" => Some((
            "IntPtr",
            std::mem::size_of::<isize>(),
            std::mem::align_of::<isize>(),
        )),
        _ => None,
    }
}

/// Convert a snake_case Rust identifier to the PascalCase used in C# mirrors.
fn snake_to_pascal(name: &str) -> String {
    let mut result = String::with_capacity(name.len());
    let mut capitalize_next = true;
    for character in name.chars() {
        if character == '_' {
            capitalize_next = true;
        } else if capitalize_next {
            result.extend(character.to_uppercase());
            capitalize_next = false;
        } else {
            result.push(character);
        }
    }
    result
}

/// Last path segment of a fully-qualified Rust type name.
fn last_path_segment(qualified: &str) -> String {
    qualified
        .rsplit("::")
        .next()
        .unwrap_or(qualified)
        .to_string()
}

// =============================================================================
// Tests
// =============================================================================

/// Regression tests for the host-side C# mirror generation.
///
/// Each test drives [`generate_module_components_csharp`] against a fresh temp
/// workspace shaped like the real repo (`<root>/optional/<module>/generated/`),
/// covering: generated content, the alignment-pad matrix, namespace splitting,
/// the up-to-date / missing / stale rewrite conditions, per-module file
/// isolation, stale-file removal when a module stops exposing components,
/// determinism, and the error paths.
#[cfg(test)]
mod tests {
    use super::*;
    use pill_engine::ComponentId;
    use std::path::{Path, PathBuf};

    /// Drive the codegen with the module's real signature; tests that do not
    /// exercise mirrored methods pass an empty method table.
    fn call_codegen(
        workspace: &Path,
        module_name: &str,
        components: &[ModuleExposedComponent],
        value_types: &[PillValueTypeDescriptor],
    ) -> Result<(), String> {
        generate_module_components_csharp(workspace, module_name, components, value_types, &[])
            .map(|_changed| ())
    }

    /// One resolved mirrored method for codegen tests.
    fn mirrored_method(
        type_name: &str,
        method_name: &str,
        return_tag: &str,
        arg_tags: &[&str],
        arg_names: &[&str],
    ) -> ResolvedMirrorMethod {
        ResolvedMirrorMethod {
            type_name: type_name.to_string(),
            method_name: method_name.to_string(),
            return_tag: return_tag.to_string(),
            arg_tags: arg_tags.iter().map(|tag| tag.to_string()).collect(),
            arg_names: arg_names.iter().map(|name| name.to_string()).collect(),
            address: 0x1234,
        }
    }

    /// Create a fresh temp workspace and the module directory under it.
    fn temp_workspace(test_name: &str, module_name: &str) -> PathBuf {
        let root =
            std::env::temp_dir().join(format!("pill_codegen_{}_{}", test_name, std::process::id()));
        let _ = std::fs::remove_dir_all(&root);
        std::fs::create_dir_all(root.join("optional").join(module_name))
            .expect("create temp module dir");
        root
    }

    /// One exposed component with a synthetic stable identity.
    fn exposed(name: &str, size: usize, align: usize) -> ModuleExposedComponent {
        ModuleExposedComponent {
            csharp_name: name.to_string(),
            component_id: ComponentId::dynamic(0xABCD_0001_0000_0001),
            size,
            align,
            fields: Vec::new(),
        }
    }

    /// One exposed component carrying a compile-time field layout.
    fn exposed_typed(
        name: &str,
        size: usize,
        align: usize,
        fields: Vec<ComponentFieldDescriptor>,
    ) -> ModuleExposedComponent {
        ModuleExposedComponent {
            csharp_name: name.to_string(),
            component_id: ComponentId::dynamic(0xABCD_0001_0000_0001),
            size,
            align,
            fields,
        }
    }

    /// One compile-time field descriptor for a typed-mirror test.
    fn field(
        name: &'static str,
        type_tag: &'static str,
        offset: usize,
        size: usize,
        align: usize,
    ) -> ComponentFieldDescriptor {
        ComponentFieldDescriptor {
            name,
            type_tag,
            offset,
            size,
            align,
            element_count: 0,
        }
    }

    /// One compile-time array-field descriptor for a typed-mirror test.
    fn array_field(
        name: &'static str,
        type_tag: &'static str,
        offset: usize,
        size: usize,
        align: usize,
        element_count: usize,
    ) -> ComponentFieldDescriptor {
        ComponentFieldDescriptor {
            name,
            type_tag,
            offset,
            size,
            align,
            element_count,
        }
    }

    fn generated_path(workspace: &Path, module_name: &str) -> PathBuf {
        workspace
            .join("optional")
            .join(module_name)
            .join("generated")
            .join(format!("{module_name}_Components.g.cs"))
    }

    /// Field layout of a synthetic `pill_core::math::Vector2f` value type.
    static VECTOR2F_FIELDS: &[ComponentFieldDescriptor] = &[
        ComponentFieldDescriptor {
            name: "x",
            type_tag: "f32",
            offset: 0,
            size: 4,
            align: 4,
            element_count: 0,
        },
        ComponentFieldDescriptor {
            name: "y",
            type_tag: "f32",
            offset: 4,
            size: 4,
            align: 4,
            element_count: 0,
        },
    ];

    fn read_generated(workspace: &Path, module_name: &str) -> String {
        std::fs::read_to_string(generated_path(workspace, module_name))
            .expect("generated file is readable")
    }

    /// The generated mirror must sit inside the optional module's own
    /// `generated` directory, not in the C# project.
    #[test]
    fn generated_file_lives_inside_the_module_directory() {
        let workspace = temp_workspace("location", "pill_spline");
        call_codegen(
            &workspace,
            "pill_spline",
            &[exposed("pill_spline.Spline", 196, 4)],
            &[],
        )
        .unwrap();
        assert!(generated_path(&workspace, "pill_spline").exists());
        assert!(generated_path(&workspace, "pill_spline")
            .starts_with(workspace.join("optional").join("pill_spline")));
    }

    /// A single component produces a struct with the right namespace, name,
    /// size, alignment pad, and the safe raw-bytes accessor.
    #[test]
    fn generates_mirror_for_a_single_component() {
        let workspace = temp_workspace("single", "pill_spline");
        call_codegen(
            &workspace,
            "pill_spline",
            &[exposed("pill_spline.Spline", 196, 4)],
            &[],
        )
        .unwrap();

        let content = read_generated(&workspace, "pill_spline");
        assert!(content.contains("namespace pill_spline {"));
        assert!(content.contains("public struct Spline"));
        assert!(content.contains("Size = 196"));
        assert!(content.contains("private readonly uint _alignmentPad;"));
        assert!(content.contains("public readonly Span<byte> Raw =>"));
        assert!(content.contains("MemoryMarshal.CreateSpan(ref Unsafe.AsRef(in this), 1)"));
    }

    /// Multiple components from the same module land in one file, each in its
    /// own namespace, with per-component size and alignment.
    #[test]
    fn generates_multiple_components_in_multiple_namespaces() {
        let workspace = temp_workspace("multi", "pill_spline");
        let components = [
            exposed("pill_spline.Spline", 196, 4),
            exposed("pill_spline.Path", 12, 4),
            exposed("tracy_nav.Segment", 16, 8),
        ];
        call_codegen(&workspace, "pill_spline", &components, &[]).unwrap();

        let content = read_generated(&workspace, "pill_spline");
        assert!(content.contains("namespace pill_spline {"));
        assert!(content.contains("namespace tracy_nav {"));
        assert!(content.contains("public struct Spline"));
        assert!(content.contains("public struct Path"));
        assert!(content.contains("public struct Segment"));
        assert!(content.contains("Size = 196"));
        assert!(content.contains("Size = 12"));
        assert!(content.contains("Size = 16"));
        // align 8 uses a ulong pad.
        assert!(content.contains("private readonly ulong _alignmentPad;"));
    }

    /// The alignment pad primitive must match each supported alignment, since
    /// C# struct alignment is driven by fields.
    #[test]
    fn alignment_pad_matches_each_supported_alignment() {
        for (align, expected_pad) in [
            (1usize, "byte"),
            (2usize, "ushort"),
            (4usize, "uint"),
            (8usize, "ulong"),
        ] {
            let workspace = temp_workspace(&format!("align_{align}"), "pill_spline");
            call_codegen(
                &workspace,
                "pill_spline",
                &[exposed("pill_spline.Spline", 16, align)],
                &[],
            )
            .unwrap();
            let content = read_generated(&workspace, "pill_spline");
            assert!(
                content.contains(&format!("private readonly {expected_pad} _alignmentPad;")),
                "alignment {align} must use a {expected_pad} pad field"
            );
        }
    }

    /// An alignment with no C# primitive is rejected and writes nothing.
    #[test]
    fn unsupported_alignment_is_rejected() {
        let workspace = temp_workspace("bad_align", "pill_spline");
        let result = call_codegen(
            &workspace,
            "pill_spline",
            &[exposed("pill_spline.Spline", 16, 3)],
            &[],
        );
        let error = result.expect_err("alignment 3 is unsupported");
        assert!(error.contains("unsupported alignment"));
        assert!(
            !generated_path(&workspace, "pill_spline").exists(),
            "a rejected generation must not write a file"
        );
    }

    /// A derived C# name without a namespace separator is rejected.
    #[test]
    fn name_without_namespace_is_rejected() {
        let workspace = temp_workspace("no_namespace", "pill_spline");
        let result = call_codegen(&workspace, "pill_spline", &[exposed("Spline", 4, 4)], &[]);
        let error = result.expect_err("a name without '.' cannot be namespaced");
        assert!(error.contains("no namespace separator"));
    }

    /// A typed component emits an explicit-layout struct with one C# field per
    /// Rust field, each carrying its byte offset, plus the Raw accessor.
    #[test]
    fn typed_mirror_emits_explicit_fields() {
        let workspace = temp_workspace("typed", "pill_spline");
        let component = exposed_typed(
            "pill_spline.Physics",
            24,
            4,
            vec![
                field("position_x", "f32", 0, 4, 4),
                field("position_y", "f32", 4, 4, 4),
                field("active", "bool", 8, 1, 1),
                field("score", "u64", 16, 8, 8),
            ],
        );
        call_codegen(&workspace, "pill_spline", &[component], &[]).unwrap();

        let content = read_generated(&workspace, "pill_spline");
        assert!(content.contains("LayoutKind.Explicit, Size = 24"));
        assert!(content.contains("[FieldOffset(0)] public float PositionX;"));
        assert!(content.contains("[FieldOffset(4)] public float PositionY;"));
        // bool maps to a raw byte in the ABI mirror.
        assert!(content.contains("[FieldOffset(8)] public byte Active;"));
        assert!(content.contains("[FieldOffset(16)] public ulong Score;"));
        assert!(content.contains("public readonly Span<byte> Raw =>"));
    }

    /// An array field is flattened into one C# field per element, with each
    /// element's own byte offset.
    #[test]
    fn typed_mirror_flattens_arrays() {
        let workspace = temp_workspace("array", "pill_spline");
        let component = exposed_typed(
            "pill_spline.Probe",
            12,
            4,
            vec![array_field("samples", "array:f32", 0, 12, 4, 3)],
        );
        call_codegen(&workspace, "pill_spline", &[component], &[]).unwrap();

        let content = read_generated(&workspace, "pill_spline");
        assert!(content.contains("[FieldOffset(0)] public float Samples0;"));
        assert!(content.contains("[FieldOffset(4)] public float Samples1;"));
        assert!(content.contains("[FieldOffset(8)] public float Samples2;"));
    }

    /// A `struct:` field whose type carries a `PillMirror` descriptor emits a
    /// typed nested struct (recursively) before the component.
    #[test]
    fn typed_mirror_emits_nested_value_types() {
        let workspace = temp_workspace("nested", "pill_spline");
        let component = exposed_typed(
            "pill_spline.Path",
            24,
            4,
            vec![
                field("start", "struct:pill_core::math::Vector2f", 0, 8, 4),
                field("end", "struct:pill_core::math::Vector2f", 8, 8, 4),
                field("kind", "u32", 20, 4, 4),
            ],
        );
        let value_types = [PillValueTypeDescriptor {
            type_name: "pill_core::math::Vector2f",
            size: 8,
            align: 4,
            fields: VECTOR2F_FIELDS,
        }];
        call_codegen(&workspace, "pill_spline", &[component], &value_types).unwrap();

        let content = read_generated(&workspace, "pill_spline");
        // The nested struct is emitted once, before the component.
        let nested_index = content
            .find("public struct Vector2f")
            .expect("nested struct");
        let component_index = content
            .find("public struct Path")
            .expect("component struct");
        assert!(
            nested_index < component_index,
            "nested type must precede its user"
        );
        assert!(content.contains("[FieldOffset(0)] public float X;"));
        assert!(content.contains("[FieldOffset(4)] public float Y;"));
        assert!(content.contains("[FieldOffset(0)] public Vector2f Start;"));
        assert!(content.contains("[FieldOffset(8)] public Vector2f End;"));
        assert!(content.contains("[FieldOffset(20)] public uint Kind;"));
    }

    /// A `struct:` field with no `PillMirror` descriptor (a foreign type, an
    /// enum, or a struct that never derived) degrades to an opaque blob of the
    /// field's size so the mirror still compiles and stays size-correct.
    #[test]
    fn typed_mirror_falls_back_to_opaque_nested() {
        let workspace = temp_workspace("opaque", "pill_spline");
        let component = exposed_typed(
            "pill_spline.Blob",
            12,
            4,
            vec![field("foreign", "struct:glam::vec3::Vec3", 0, 12, 4)],
        );
        call_codegen(&workspace, "pill_spline", &[component], &[]).unwrap();

        let content = read_generated(&workspace, "pill_spline");
        assert!(content.contains("public struct Vec3"));
        assert!(content.contains("Size = 12"));
        assert!(content.contains("[FieldOffset(0)] public Vec3 Foreign;"));
    }

    /// An array of nested structs resolves each element through the inventory
    /// and validates the element size against the descriptor.
    #[test]
    fn typed_mirror_handles_arrays_of_nested_structs() {
        let workspace = temp_workspace("array_nested", "pill_spline");
        let component = exposed_typed(
            "pill_spline.Track",
            24,
            4,
            vec![array_field(
                "points",
                "array:struct:pill_core::math::Vector2f",
                0,
                24,
                4,
                3,
            )],
        );
        let value_types = [PillValueTypeDescriptor {
            type_name: "pill_core::math::Vector2f",
            size: 8,
            align: 4,
            fields: VECTOR2F_FIELDS,
        }];
        call_codegen(&workspace, "pill_spline", &[component], &value_types).unwrap();

        let content = read_generated(&workspace, "pill_spline");
        assert!(content.contains("[FieldOffset(0)] public Vector2f Points0;"));
        assert!(content.contains("[FieldOffset(8)] public Vector2f Points1;"));
        assert!(content.contains("[FieldOffset(16)] public Vector2f Points2;"));
    }

    /// A nested descriptor whose size disagrees with the referencing field is
    /// a drift bug and must fail loudly rather than emit a wrong mirror.
    #[test]
    fn typed_mirror_rejects_nested_size_mismatch() {
        let workspace = temp_workspace("mismatch", "pill_spline");
        let component = exposed_typed(
            "pill_spline.Path",
            8,
            4,
            vec![field("start", "struct:pill_core::math::Vector2f", 0, 8, 4)],
        );
        let value_types = [PillValueTypeDescriptor {
            type_name: "pill_core::math::Vector2f",
            size: 12,
            align: 4,
            fields: VECTOR2F_FIELDS,
        }];
        let result = call_codegen(&workspace, "pill_spline", &[component], &value_types);
        let error = result.expect_err("a size mismatch must be rejected");
        assert!(error.contains("rebuild the module"));
    }

    /// Value types declared by the module are mirrored even when no component
    /// references them, so `#[derive(PillMirror)]` alone exposes a type to C#.
    #[test]
    fn mirrors_value_types_not_referenced_by_components() {
        let workspace = temp_workspace("standalone_value", "pill_spline");
        let component = exposed_typed(
            "pill_spline.Spline",
            200,
            4,
            vec![field("count", "u32", 0, 4, 4), field("elo", "f32", 4, 4, 4)],
        );
        let value_types = [PillValueTypeDescriptor {
            type_name: "pill_spline::OmoMO",
            size: 16,
            align: 8,
            fields: &[
                ComponentFieldDescriptor {
                    name: "x",
                    type_tag: "u64",
                    offset: 0,
                    size: 8,
                    align: 8,
                    element_count: 0,
                },
                ComponentFieldDescriptor {
                    name: "y",
                    type_tag: "u64",
                    offset: 8,
                    size: 8,
                    align: 8,
                    element_count: 0,
                },
            ],
        }];
        call_codegen(&workspace, "pill_spline", &[component], &value_types).unwrap();

        let content = read_generated(&workspace, "pill_spline");
        assert!(content.contains("public struct OmoMO"));
        assert!(content.contains("[FieldOffset(0)] public ulong X;"));
        assert!(content.contains("[FieldOffset(8)] public ulong Y;"));
        assert!(content.contains("public struct Spline"));
    }

    /// Overlapping sibling fields (a malformed descriptor) are rejected before
    /// any C# file is written.
    #[test]
    fn typed_mirror_rejects_overlapping_fields() {
        let workspace = temp_workspace("overlap", "pill_spline");
        let component = exposed_typed(
            "pill_spline.Bad",
            8,
            4,
            vec![field("a", "u64", 0, 8, 8), field("b", "u32", 4, 4, 4)],
        );
        let result = call_codegen(&workspace, "pill_spline", &[component], &[]);
        let error = result.expect_err("overlapping fields must be rejected");
        assert!(error.contains("overlap"));
    }

    /// A field that runs past the end of the type is a malformed descriptor.
    #[test]
    fn typed_mirror_rejects_out_of_bounds_field() {
        let workspace = temp_workspace("bounds", "pill_spline");
        let component = exposed_typed(
            "pill_spline.Bad",
            4,
            4,
            vec![field("a", "u32", 0, 4, 4), field("b", "u32", 4, 4, 4)],
        );
        let result = call_codegen(&workspace, "pill_spline", &[component], &[]);
        let error = result.expect_err("an out-of-bounds field must be rejected");
        assert!(error.contains("outside the"));
    }

    /// Over-aligned layouts cannot be expressed in C# and are rejected with a
    /// message naming the type.
    #[test]
    fn typed_mirror_rejects_over_alignment() {
        let workspace = temp_workspace("over_align", "pill_spline");
        let component = exposed_typed("pill_spline.Big", 32, 16, vec![field("a", "u32", 0, 4, 4)]);
        let result = call_codegen(&workspace, "pill_spline", &[component], &[]);
        let error = result.expect_err("alignment 16 is not expressible");
        assert!(error.contains("alignment"));
    }

    /// Regenerating with identical content must not touch the file (mtime
    /// preserved), which keeps the committed bootstrap clean.
    #[test]
    fn skips_rewrite_when_content_is_identical() {
        let workspace = temp_workspace("up_to_date", "pill_spline");
        let components = [exposed("pill_spline.Spline", 196, 4)];
        call_codegen(&workspace, "pill_spline", &components, &[]).unwrap();

        let before = std::fs::metadata(generated_path(&workspace, "pill_spline"))
            .unwrap()
            .modified()
            .unwrap();
        call_codegen(&workspace, "pill_spline", &components, &[]).unwrap();
        let after = std::fs::metadata(generated_path(&workspace, "pill_spline"))
            .unwrap()
            .modified()
            .unwrap();
        assert_eq!(
            before, after,
            "identical content must not rewrite the generated file"
        );
    }

    /// A missing file is regenerated.
    #[test]
    fn writes_when_file_is_missing() {
        let workspace = temp_workspace("missing", "pill_spline");
        let components = [exposed("pill_spline.Spline", 196, 4)];
        call_codegen(&workspace, "pill_spline", &components, &[]).unwrap();
        std::fs::remove_file(generated_path(&workspace, "pill_spline")).unwrap();

        call_codegen(&workspace, "pill_spline", &components, &[]).unwrap();
        assert!(generated_path(&workspace, "pill_spline").exists());
    }

    /// A layout change (size/align) triggers a rewrite with the new values.
    #[test]
    fn rewrites_when_layout_changed() {
        let workspace = temp_workspace("layout_changed", "pill_spline");
        call_codegen(
            &workspace,
            "pill_spline",
            &[exposed("pill_spline.Spline", 196, 4)],
            &[],
        )
        .unwrap();
        assert!(read_generated(&workspace, "pill_spline").contains("Size = 196"));

        call_codegen(
            &workspace,
            "pill_spline",
            &[exposed("pill_spline.Spline", 200, 8)],
            &[],
        )
        .unwrap();
        let content = read_generated(&workspace, "pill_spline");
        assert!(content.contains("Size = 200"));
        assert!(content.contains("private readonly ulong _alignmentPad;"));
    }

    /// Different modules write separate files, and one module's mirror never
    /// leaks into another's.
    #[test]
    fn writes_separate_files_per_module() {
        let workspace = temp_workspace("per_module", "pill_spline");
        std::fs::create_dir_all(workspace.join("optional").join("other_module")).unwrap();
        call_codegen(
            &workspace,
            "pill_spline",
            &[exposed("pill_spline.Spline", 196, 4)],
            &[],
        )
        .unwrap();
        call_codegen(
            &workspace,
            "other_module",
            &[exposed("other_module.Gadget", 8, 4)],
            &[],
        )
        .unwrap();

        let spline_file = read_generated(&workspace, "pill_spline");
        let gadget_file = read_generated(&workspace, "other_module");
        assert!(spline_file.contains("Spline"));
        assert!(!spline_file.contains("Gadget"));
        assert!(gadget_file.contains("Gadget"));
        assert!(!gadget_file.contains("Spline"));
    }

    /// A module that stops exposing components removes its stale mirror file
    /// so a vanished binding cannot linger in the C# project.
    #[test]
    fn empty_exposure_removes_stale_file() {
        let workspace = temp_workspace("emptied", "pill_spline");
        call_codegen(
            &workspace,
            "pill_spline",
            &[exposed("pill_spline.Spline", 196, 4)],
            &[],
        )
        .unwrap();
        assert!(generated_path(&workspace, "pill_spline").exists());

        call_codegen(&workspace, "pill_spline", &[], &[]).unwrap();
        assert!(
            !generated_path(&workspace, "pill_spline").exists(),
            "a module exposing nothing must not keep a stale mirror"
        );
    }

    /// The same input produces byte-identical output on fresh workspaces, so
    /// regeneration never dirties the committed bootstrap.
    #[test]
    fn output_is_deterministic() {
        let first = temp_workspace("deterministic_a", "pill_spline");
        let second = temp_workspace("deterministic_b", "pill_spline");
        let components = [
            exposed("pill_spline.Spline", 196, 4),
            exposed("pill_spline.Path", 12, 4),
        ];
        call_codegen(&first, "pill_spline", &components, &[]).unwrap();
        call_codegen(&second, "pill_spline", &components, &[]).unwrap();

        assert_eq!(
            read_generated(&first, "pill_spline"),
            read_generated(&second, "pill_spline")
        );
    }

    /// Mirrored methods become typed C# instance methods that resolve the
    /// module's trampoline through `MirrorMethods` and pin the struct for the
    /// call. A value type without methods emits no method block.
    #[test]
    fn mirrored_methods_are_emitted_on_value_types() {
        static FIELDS: &[ComponentFieldDescriptor] = &[
            ComponentFieldDescriptor {
                name: "x",
                type_tag: "u64",
                offset: 0,
                size: 8,
                align: 8,
                element_count: 0,
            },
            ComponentFieldDescriptor {
                name: "y",
                type_tag: "u64",
                offset: 8,
                size: 8,
                align: 8,
                element_count: 0,
            },
        ];
        let workspace = temp_workspace("mirror_methods", "pill_spline");
        let value_types = [PillValueTypeDescriptor {
            type_name: "pill_spline::OmoMO",
            size: 16,
            align: 8,
            fields: FIELDS,
        }];
        let methods = [
            mirrored_method("pill_spline::OmoMO", "get_sum", "u64", &[], &[]),
            mirrored_method(
                "pill_spline::OmoMO",
                "add",
                "u32",
                &["u32", "f32"],
                &["amount", "scale"],
            ),
            mirrored_method("pill_spline::Other", "unused", "", &[], &[]),
        ];
        generate_module_components_csharp(
            &workspace,
            "pill_spline",
            &[exposed("pill_spline.Spline", 200, 4)],
            &value_types,
            &methods,
        )
        .unwrap();

        let content = read_generated(&workspace, "pill_spline");
        // Instance method + delegate, PascalCased, resolving by Rust names.
        assert!(content.contains("public ulong GetSum()"));
        assert!(content.contains("public delegate ulong OmoMOGetSumDelegate(IntPtr self);"));
        assert!(content.contains(
            "global::TracyLive.MirrorMethods.Resolve<OmoMOGetSumDelegate>(\"pill_spline::OmoMO\", \"get_sum\")"
        ));
        // Argument-carrying method: the Rust parameter names survive into both
        // the delegate and the instance method, which forwards them by value.
        assert!(content.contains("public uint Add(uint amount, float scale)"));
        assert!(content.contains(
            "public delegate uint OmoMOAddDelegate(IntPtr self, uint amount, float scale);"
        ));
        assert!(content.contains("mirror(handle.AddrOfPinnedObject(), amount, scale);"));
        // The pinned-box call keeps the whole body in safe C#.
        assert!(content.contains(
            "global::System.Runtime.InteropServices.GCHandle.Alloc(boxed, global::System.Runtime.InteropServices.GCHandleType.Pinned)"
        ));
        assert!(content.contains("handle.AddrOfPinnedObject()"));
        // Methods of a type that is never emitted must not appear.
        assert!(!content.contains("Unused"));
    }

    /// A void-returning mirrored method emits a `void` delegate and a call
    /// that does not return a value.
    #[test]
    fn mirrored_method_void_return_is_emitted() {
        static FIELDS: &[ComponentFieldDescriptor] = &[ComponentFieldDescriptor {
            name: "x",
            type_tag: "u64",
            offset: 0,
            size: 8,
            align: 8,
            element_count: 0,
        }];
        let workspace = temp_workspace("mirror_method_void", "pill_spline");
        let value_types = [PillValueTypeDescriptor {
            type_name: "pill_spline::OmoMO",
            size: 16,
            align: 8,
            fields: FIELDS,
        }];
        let methods = [mirrored_method(
            "pill_spline::OmoMO",
            "reset",
            "",
            &["u64"],
            &["countdown"],
        )];
        generate_module_components_csharp(
            &workspace,
            "pill_spline",
            &[exposed("pill_spline.Spline", 200, 4)],
            &value_types,
            &methods,
        )
        .unwrap();

        let content = read_generated(&workspace, "pill_spline");
        assert!(content.contains("public void Reset(ulong countdown)"));
        assert!(content
            .contains("public delegate void OmoMOResetDelegate(IntPtr self, ulong countdown);"));
        assert!(content.contains("mirror(handle.AddrOfPinnedObject(), countdown);"));
    }

    /// A Rust parameter name that is a C# reserved keyword (or is absent) must
    /// not be emitted verbatim - the generated project would not compile.
    #[test]
    fn csharp_parameter_names_are_keyword_safe() {
        assert_eq!(csharp_parameter_name(0, "alpha"), "alpha");
        assert_eq!(csharp_parameter_name(2, "event"), "arg2");
        assert_eq!(csharp_parameter_name(1, "string"), "arg1");
        assert_eq!(csharp_parameter_name(0, "ref"), "arg0");
        assert_eq!(csharp_parameter_name(1, ""), "arg1");
    }

    /// The codegen reports whether the mirror file on disk changed, so the
    /// reload path can queue a C# rebuild only when the module's mirror
    /// surface actually moved: a matching re-run reports no change, and adding
    /// a method (or a first run on a fresh workspace) reports a change.
    #[test]
    fn codegen_reports_whether_the_mirror_changed() {
        static FIELDS: &[ComponentFieldDescriptor] = &[ComponentFieldDescriptor {
            name: "x",
            type_tag: "u64",
            offset: 0,
            size: 8,
            align: 8,
            element_count: 0,
        }];
        let workspace = temp_workspace("mirror_changed_flag", "pill_spline");
        let component = exposed("pill_spline.OmoMO", 16, 8);
        let value_types = [PillValueTypeDescriptor {
            type_name: "pill_spline::OmoMO",
            size: 16,
            align: 8,
            fields: FIELDS,
        }];
        let methods_without = [mirrored_method(
            "pill_spline::OmoMO",
            "get_sum",
            "u64",
            &[],
            &[],
        )];
        let methods_with = [
            mirrored_method("pill_spline::OmoMO", "get_sum", "u64", &[], &[]),
            mirrored_method("pill_spline::OmoMO", "get_b", "u64", &[], &[]),
        ];

        // First write on a fresh workspace always reports a change.
        assert!(generate_module_components_csharp(
            &workspace,
            "pill_spline",
            &[component.clone()],
            &value_types,
            &methods_without,
        )
        .unwrap());
        // Identical regeneration reports no change.
        assert!(!generate_module_components_csharp(
            &workspace,
            "pill_spline",
            &[component.clone()],
            &value_types,
            &methods_without,
        )
        .unwrap());
        // Adding a mirrored method changes the content, so it reports a change.
        assert!(generate_module_components_csharp(
            &workspace,
            "pill_spline",
            &[component],
            &value_types,
            &methods_with,
        )
        .unwrap());
        assert!(read_generated(&workspace, "pill_spline").contains("public ulong GetB()"));
    }
}
