[package]
name = "pill_master_renderer"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[lib]
crate-type = ["rlib"]

[dependencies]
pill_core = { path = "../../../pill_core" }
pill_core_macros = { path = "../../../pill_core_macros" }
pill_engine = { path = "../../../pill_engine" }
trait_type_map = { path = "../../../../../Trait-Type-Map" }

serde = { version = "1", features = ["derive"] }
thiserror = "2"
miette = { version = "7", features = ["derive"] }
glam = { version = "0.33", features = ["serde", "bytemuck"] }
winit = "0.30.12"
bytemuck = { version = "1.4", features = ["derive"] }
wgpu = "25.0.0"
pollster = "0.4"
image = { version = "0.25", default-features = false, features = ["png"] }

egui = { version = "0.32.1", optional = true }
egui-wgpu = { version = "0.32.1", features = ["winit"], optional = true }
egui-winit = { version = "0.32.1", features = ["clipboard"], optional = true }

[features]
debug_ui = ["dep:egui", "dep:egui-wgpu", "dep:egui-winit"]
