[package]
name = "italian_brainrot"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
glam = "0.33"
pill_engine = { path = "../../modules/pill_engine" }
pill_master_renderer = { path = "../../modules/extensions/rendering/pill_master_renderer", default-features = false }
serde = { version = "1", features = ["derive"] }
trait_type_map = { path = "../../../Trait-Type-Map" }

[features]
