[package]
name = "pill_standalone"
version = "0.1.0"
edition = "2021"

[dependencies]
ecs_hybrid = { path = "../engine" }
host = { path = "../host" }
wgpu = { version = "26.0.1", optional = true }
winit = { version = "0.30", optional = true }
pollster = { version = "0.4", optional = true }

[features]
rendering = [
    "dep:wgpu",
    "dep:winit",
    "dep:pollster",
    "ecs_hybrid/rendering",
    "host/rendering",
]
