[package]
name = "pill_standalone"
version = "0.1.0"
edition = "2021"

[dependencies]
pill_engine = { path = "../engine" }
host = { package = "pill_host", path = "../host" }
wgpu = { version = "26.0.1", optional = true }
winit = { version = "0.30", optional = true }
pollster = { version = "0.4", optional = true }

[features]
rendering = [
    "dep:wgpu",
    "dep:winit",
    "dep:pollster",
    "pill_engine/rendering",
    "host/rendering",
]
