//! Typed error system shared by every Pill workspace crate, generated from
//! one semantic message definition per variant.
//!
//! # Responsibilities
//!
//! - Define the semantic rendering protocol ([`SemanticRole`],
//!   [`MessageRenderer`], [`EngineMessage`]) used by generated code.
//! - Provide the plain and terminal renderers plus the miette presentation
//!   adapter and report handler.
//! - Declare every subsystem error ([`ConfigError`], [`BuildError`],
//!   [`LibraryError`], [`WatcherError`], [`CSharpError`]) and their
//!   transparent composition [`HostError`].
//!
//! # Design
//!
//! Every error variant carries a single `#[message(...)]` definition. The
//! `#[engine_error]` macro generates the plain `Display` message, a stable
//! `namespace::variant` diagnostic code, and an [`EngineMessage`]
//! implementation that renders the same definition with semantic roles.
//! Subsystem errors compose into [`HostError`] through transparent
//! `#[from]` wrappers, so `?` works across boundaries while the leaf error
//! and its source chain survive. Styling lives only in the renderers; error
//! definitions never import a styling crate.

// Standard library
use std::fmt;

// External crates
use colored::Colorize;
use pill_core_macros::engine_error;

// =============================================================================
// Semantic Rendering Protocol
// =============================================================================

/// Semantic role of one message token.
///
/// Roles describe meaning, never appearance. The renderer decides how each
/// role looks in its target environment.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SemanticRole {
    /// General engine objects: `Scene`, `Component`, `System`, `Resource`.
    General,
    /// Specific engine objects or types: `Texture`, `Surface`, `Handle`.
    Specific,
    /// Module-level concepts: `Engine`, `Renderer`, `Window`.
    Module,
    /// User or domain names: file paths, scene names, symbol names.
    Name,
}

/// Sink for one semantically rendered error message.
///
/// Generated `EngineMessage` implementations call this protocol directly;
/// no intermediate vector or reconstructed string is ever created.
pub trait MessageRenderer {
    /// Write one plain-text fragment.
    ///
    /// # Errors
    ///
    /// Returns an error if the underlying writer fails.
    fn text(&mut self, text: &str) -> fmt::Result;

    /// Write one value under a semantic role.
    ///
    /// # Errors
    ///
    /// Returns an error if the underlying writer fails.
    fn styled(&mut self, role: SemanticRole, value: &dyn fmt::Display) -> fmt::Result;

    /// Write one plain dynamic value.
    ///
    /// # Errors
    ///
    /// Returns an error if the underlying writer fails.
    fn value(&mut self, value: &dyn fmt::Display) -> fmt::Result;

    /// Write the debug representation of one dynamic value.
    ///
    /// # Errors
    ///
    /// Returns an error if the underlying writer fails.
    fn debug_value(&mut self, value: &dyn fmt::Debug) -> fmt::Result;
}

/// Rendering interface generated by `#[engine_error]` for every error enum.
///
/// Generated implementations render the single semantic message definition
/// through [`MessageRenderer`], so plain and styled output always agree.
pub trait EngineMessage {
    /// Render the single semantic message definition into `renderer`.
    ///
    /// # Errors
    ///
    /// Returns an error if `renderer` reports a write failure.
    fn render_message(&self, renderer: &mut dyn MessageRenderer) -> fmt::Result;

    /// Convenience rendering into the plain renderer, for logs and tests.
    ///
    /// # Examples
    ///
    /// ```
    /// use pill_core::error::{BuildError, EngineMessage};
    ///
    /// let message = BuildError::Cancelled.to_plain_message();
    /// assert_eq!(
    ///     message,
    ///     "build cancelled: sources changed again during compilation"
    /// );
    /// ```
    fn to_plain_message(&self) -> String {
        let mut output = String::new();
        let mut renderer = PlainMessageRenderer {
            output: &mut output,
        };
        // Rendering into a String can never fail.
        let _ = self.render_message(&mut renderer);
        output
    }
}

/// Renderer that ignores semantic roles and keeps values verbatim.
///
/// Used by tests, logs, and any non-styled environment; every message
/// degrades cleanly to plain text.
pub struct PlainMessageRenderer<'a, W> {
    output: &'a mut W,
}

impl<W: fmt::Write> PlainMessageRenderer<'_, W> {
    /// Wrap a writer for plain rendering.
    ///
    /// # Examples
    ///
    /// ```
    /// use pill_core::error::{BuildError, EngineMessage, PlainMessageRenderer};
    ///
    /// let mut output = String::new();
    /// {
    ///     let mut renderer = PlainMessageRenderer::new(&mut output);
    ///     BuildError::Cancelled.render_message(&mut renderer).unwrap();
    /// }
    /// assert_eq!(
    ///     output,
    ///     "build cancelled: sources changed again during compilation"
    /// );
    /// ```
    pub fn new(output: &mut W) -> PlainMessageRenderer<'_, W> {
        PlainMessageRenderer { output }
    }
}

impl<W: fmt::Write> MessageRenderer for PlainMessageRenderer<'_, W> {
    fn text(&mut self, text: &str) -> fmt::Result {
        self.output.write_str(text)
    }

    fn styled(&mut self, _role: SemanticRole, value: &dyn fmt::Display) -> fmt::Result {
        write!(self.output, "{value}")
    }

    fn value(&mut self, value: &dyn fmt::Display) -> fmt::Result {
        write!(self.output, "{value}")
    }

    fn debug_value(&mut self, value: &dyn fmt::Debug) -> fmt::Result {
        write!(self.output, "{value:?}")
    }
}

/// Terminal renderer carrying the project's visual style per semantic role.
///
/// This module owns all terminal appearance decisions; error definitions
/// never reference colors or ANSI styling.
pub struct TerminalMessageRenderer<'a, W> {
    output: &'a mut W,
}

impl<W: fmt::Write> TerminalMessageRenderer<'_, W> {
    /// Wrap a writer for styled terminal rendering.
    ///
    /// # Examples
    ///
    /// ```
    /// use pill_core::error::{BuildError, EngineMessage, TerminalMessageRenderer};
    ///
    /// let mut output = String::new();
    /// {
    ///     let mut renderer = TerminalMessageRenderer::new(&mut output);
    ///     BuildError::Cancelled.render_message(&mut renderer).unwrap();
    /// }
    /// assert!(output.contains("build cancelled"));
    /// ```
    pub fn new(output: &mut W) -> TerminalMessageRenderer<'_, W> {
        TerminalMessageRenderer { output }
    }
}

impl<W: fmt::Write> MessageRenderer for TerminalMessageRenderer<'_, W> {
    fn text(&mut self, text: &str) -> fmt::Result {
        self.output.write_str(text)
    }

    fn styled(&mut self, role: SemanticRole, value: &dyn fmt::Display) -> fmt::Result {
        let value = value.to_string();
        let styled = match role {
            SemanticRole::General => value.bright_cyan().to_string(),
            SemanticRole::Specific => value.truecolor(95, 210, 90).to_string(),
            SemanticRole::Module => value.truecolor(180, 25, 100).bold().to_string(),
            SemanticRole::Name => format!("\"{value}\"").truecolor(190, 220, 160).to_string(),
        };
        self.output.write_str(&styled)
    }

    fn value(&mut self, value: &dyn fmt::Display) -> fmt::Result {
        write!(self.output, "{value}")
    }

    fn debug_value(&mut self, value: &dyn fmt::Debug) -> fmt::Result {
        write!(self.output, "{value:?}")
    }
}

// =============================================================================
// Miette Presentation
// =============================================================================

/// Presentation-only proxy that renders an engine error's primary message
/// with semantic terminal styling while keeping its diagnostic metadata.
///
/// The original error's `Display` stays plain; this adapter is allowed to
/// produce styled output because it is the reporting boundary, not the
/// domain error itself.
pub struct StyledDiagnosticProxy<E> {
    inner: E,
}

impl<E> StyledDiagnosticProxy<E> {
    /// Wrap an engine error for styled terminal reporting.
    ///
    /// # Examples
    ///
    /// ```
    /// use pill_core::error::{BuildError, StyledDiagnosticProxy};
    ///
    /// let proxy = StyledDiagnosticProxy::new(BuildError::Cancelled);
    /// assert!(matches!(proxy.into_inner(), BuildError::Cancelled));
    /// ```
    pub fn new(inner: E) -> Self {
        Self { inner }
    }

    /// Unwrap the original error.
    pub fn into_inner(self) -> E {
        self.inner
    }
}

impl<E> fmt::Display for StyledDiagnosticProxy<E>
where
    E: EngineMessage,
{
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        // Step 1: Render the semantic message into a private buffer; the inner
        // scope ends the mutable borrow before the formatter is written.
        let mut buffer = String::new();
        {
            let mut renderer = TerminalMessageRenderer::new(&mut buffer);
            self.inner.render_message(&mut renderer)?;
        }
        // Step 2: Emit the finished buffer to the caller's formatter.
        formatter.write_str(&buffer)
    }
}

impl<E: fmt::Debug> fmt::Debug for StyledDiagnosticProxy<E> {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        fmt::Debug::fmt(&self.inner, formatter)
    }
}

impl<E> std::error::Error for StyledDiagnosticProxy<E>
where
    E: EngineMessage + miette::Diagnostic,
{
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        self.inner.source()
    }
}

impl<E> miette::Diagnostic for StyledDiagnosticProxy<E>
where
    E: EngineMessage + miette::Diagnostic,
{
    fn code<'a>(&'a self) -> Option<Box<dyn fmt::Display + 'a>> {
        self.inner.code()
    }

    fn severity(&self) -> Option<miette::Severity> {
        self.inner.severity()
    }

    fn help<'a>(&'a self) -> Option<Box<dyn fmt::Display + 'a>> {
        self.inner.help()
    }

    fn url<'a>(&'a self) -> Option<Box<dyn fmt::Display + 'a>> {
        self.inner.url()
    }

    fn source_code(&self) -> Option<&dyn miette::SourceCode> {
        self.inner.source_code()
    }

    fn labels(&self) -> Option<Box<dyn Iterator<Item = miette::LabeledSpan> + '_>> {
        self.inner.labels()
    }

    fn related<'a>(&'a self) -> Option<Box<dyn Iterator<Item = &'a dyn miette::Diagnostic> + 'a>> {
        self.inner.related()
    }

    fn diagnostic_source(&self) -> Option<&dyn miette::Diagnostic> {
        self.inner.diagnostic_source()
    }
}

/// Terminal-aware report handler combining the engine semantic message with
/// miette's diagnostic metadata.
///
/// Stage A renders the semantic primary message through
/// [`StyledDiagnosticProxy`] and keeps miette's graphical rendering for
/// codes, help, sources, and cause chains.
#[derive(Debug)]
pub struct EngineReportHandler {
    inner: miette::GraphicalReportHandler,
}

impl Default for EngineReportHandler {
    fn default() -> Self {
        Self {
            inner: miette::GraphicalReportHandler::new(),
        }
    }
}

impl miette::ReportHandler for EngineReportHandler {
    fn debug(
        &self,
        error: &dyn miette::Diagnostic,
        formatter: &mut fmt::Formatter<'_>,
    ) -> fmt::Result {
        self.inner.debug(error, formatter)
    }
}

// =============================================================================
// Subsystem Errors
// =============================================================================

/// Configuration-validation failures for project-module setups.
///
/// Raised before any build work begins, so a misconfigured module fails fast
/// with a precise diagnostic instead of a confusing runtime error.
#[engine_error(namespace = host::config)]
pub enum ConfigError {
    /// The configured module name is empty.
    #[message("module name must not be empty")]
    EmptyModuleName,

    /// The configured watch directory is empty.
    #[message("watch directory must not be empty")]
    EmptyWatchDirectory,

    /// The configured build command is empty.
    #[message("build command must not be empty")]
    EmptyBuildCommand,

    /// A required configuration environment variable was not set.
    #[message("required environment variable ", value(variable), " is not set")]
    MissingEnvironmentVariable { variable: &'static str },

    /// The configured project directory does not exist.
    #[message("project directory does not exist: ", name_style(path))]
    ProjectDirectoryMissing { path: String },

    /// The project directory contains no Cargo.toml or .csproj manifest.
    #[message(
        "no project manifest (Cargo.toml or .csproj) found in ",
        name_style(path)
    )]
    ProjectManifestMissing { path: String },

    /// The project manifest could not be read.
    #[message("failed to read project manifest ", name_style(path))]
    ProjectManifestReadFailed {
        path: String,
        #[source]
        source: std::io::Error,
    },

    /// The project manifest does not declare a package name.
    #[message(
        "project manifest ",
        name_style(path),
        " does not declare a package name"
    )]
    ProjectPackageNameMissing { path: String },

    /// The generated host workspace member for a native project could not be
    /// created or written.
    #[message("failed to create generated host project member at ", name_style(path))]
    HostProjectMemberCreationFailed {
        path: String,
        #[source]
        source: std::io::Error,
    },

    /// A `path` dependency in the project manifest does not resolve to an
    /// existing directory once rewritten for the generated workspace member.
    ///
    /// Reported instead of writing the member, because a member Cargo cannot
    /// load breaks every build in the workspace - including the one that would
    /// replace it.
    #[message(
        "project manifest ",
        name_style(manifest_path),
        " declares dependency ",
        name_style(dependency),
        " at a path that does not exist: ",
        name_style(resolved_path)
    )]
    ProjectDependencyPathMissing {
        manifest_path: String,
        dependency: String,
        resolved_path: String,
    },

    /// The project's settings file does not exist.
    #[message("project settings file not found at ", name_style(path))]
    ProjectSettingsFileMissing { path: String },

    /// The project's settings file could not be read.
    #[message("failed to read project settings file ", name_style(path))]
    ProjectSettingsFileReadFailed {
        path: String,
        #[source]
        source: std::io::Error,
    },

    /// The project's settings file could not be parsed.
    #[message(
        "failed to parse project settings file ",
        name_style(path),
        ": ",
        value(details)
    )]
    ProjectSettingsFileParseFailed { path: String, details: String },

    /// The project's settings file does not declare a `name`.
    #[message(
        "project settings file ",
        name_style(path),
        " must declare a `name` (used for the window title)"
    )]
    MissingProjectName { path: String },

    /// The project's settings file's `build_binary_name` is missing or not
    /// filename-safe.
    #[message(
        "project settings file ",
        name_style(path),
        " must declare a `build_binary_name` with only letters, digits and underscores (no spaces or special characters)"
    )]
    InvalidBuildBinaryName { path: String },
}

/// Project-module build execution failures.
///
/// Covers spawn, wait, timeout, cancellation, and missing-artifact failures
/// of the external command that builds a project module.
#[engine_error(namespace = host::build)]
pub enum BuildError {
    /// The build command list is empty.
    #[message("build command must not be empty")]
    EmptyCommand,

    /// The build executable could not be spawned.
    #[message("failed to spawn build command for ", name_style(name))]
    SpawnFailed {
        name: String,
        #[source]
        source: std::io::Error,
    },

    /// The build child could not be waited on.
    #[message("failed to wait for the build command of ", name_style(name))]
    WaitFailed {
        name: String,
        #[source]
        source: std::io::Error,
    },

    /// The build command exited with a non-zero status.
    #[message(
        "build command failed for ",
        name_style(name),
        " with status ",
        value(status)
    )]
    CommandFailed {
        name: String,
        status: std::process::ExitStatus,
    },

    /// The build command exceeded its wall-clock deadline.
    #[message(
        "build command for ",
        name_style(name),
        " timed out after ",
        value(seconds),
        " seconds"
    )]
    TimedOut { name: String, seconds: u64 },

    /// Sources changed again while the build was running.
    #[message("build cancelled: sources changed again during compilation")]
    Cancelled,

    /// The build succeeded but no artifact appeared at the configured path.
    #[message("shared library not found at expected path: ", name_style(path))]
    #[diagnostic(help("check the selected backend output directory in ProjectModuleConfig"))]
    OutputMissing { path: String },

    /// The built library could not be staged into its hot-load directory.
    #[message(
        "failed to copy built library ",
        name_style(source_path),
        " to hot-load path ",
        name_style(target_path)
    )]
    HotArtifactCopyFailed {
        source_path: String,
        target_path: String,
        #[source]
        source: std::io::Error,
    },
}

/// Native project-library loading and initialization failures.
///
/// Covers the temporary-directory staging, the copy into place, dynamic
/// loading, and the `project_init` entry-point contract.
#[engine_error(namespace = host::library)]
pub enum LibraryError {
    /// The per-process temporary directory could not be created.
    #[message(
        "failed to prepare temporary library directory ",
        name_style(directory)
    )]
    TemporaryDirectory {
        directory: String,
        #[source]
        source: std::io::Error,
    },

    /// The built library could not be copied to its temporary path.
    #[message(
        "failed to copy built library ",
        name_style(source_path),
        " to ",
        name_style(target_path)
    )]
    CopyFailed {
        source_path: String,
        target_path: String,
        #[source]
        source: std::io::Error,
    },

    /// The temporary copy is not a loadable native library.
    #[message("failed to load native project library from ", name_style(path))]
    LoadFailed {
        path: String,
        #[source]
        source: libloading::Error,
    },

    /// The library does not export a required entry point.
    #[message(
        "native project library is missing required export ",
        name_style(symbol)
    )]
    MissingExport {
        symbol: String,
        #[source]
        source: libloading::Error,
    },

    /// `project_init` reported a failed generation.
    #[message("project module initialization failed with status ", value(status))]
    InitializationFailed { status: u32 },
}

/// Optional-module loading and compatibility failures.
///
/// Distinct from [`LibraryError`], which covers the mechanics of mapping a
/// library: these report a broken contract between the host and a module.
#[engine_error(namespace = host::module)]
pub enum ModuleError {
    /// The module was built against a different module ABI revision.
    #[message(
        "optional module ",
        name_style(module),
        " reports ABI version ",
        value(module_version),
        " but the host requires ",
        value(host_version)
    )]
    #[diagnostic(help("rebuild the module against the current engine sources"))]
    AbiVersionMismatch {
        module: String,
        module_version: u32,
        host_version: u32,
    },

    /// The module does not export an ABI revision at all.
    #[message(
        "optional module ",
        name_style(module),
        " does not export pill_module_abi_version"
    )]
    #[diagnostic(help(
        "an optional module must export pill_module_abi_version, pill_module_init and, optionally, pill_module_update"
    ))]
    AbiVersionMissing { module: String },

    /// The module's registration entry point reported a failed generation.
    #[message(
        "optional module ",
        name_style(module),
        " initialization failed with status ",
        value(status)
    )]
    InitializationFailed { module: String, status: u32 },

    /// Two configured modules share one name.
    #[message("optional module name ", name_style(module), " is configured twice")]
    DuplicateName { module: String },
}

/// Source-watching startup failures.
///
/// Distinct from build failures: the watcher must start before any build can
/// be triggered by a source change.
#[engine_error(namespace = host::watcher)]
pub enum WatcherError {
    /// The configured watch directory does not exist.
    #[message("watch directory does not exist: ", name_style(path))]
    WatchDirectoryMissing { path: String },

    /// The platform file watcher could not be created.
    #[message("failed to create file watcher")]
    CreationFailed {
        #[source]
        source: notify::Error,
    },

    /// The watch path could not be registered.
    #[message("failed to register watch path ", name_style(path))]
    RegistrationFailed {
        path: String,
        #[source]
        source: notify::Error,
    },
}

/// Managed (C#) backend startup and registration failures.
///
/// Covers hostfxr discovery and loading, runtime delegates, the component
/// manifest exchange, and reflected managed startup.
#[engine_error(namespace = host::csharp)]
pub enum CSharpError {
    /// No hostfxr installation was found in any configured dotnet root.
    #[message("no .NET hostfxr installation found; searched the configured dotnet roots")]
    HostfxrNotFound,

    /// The `ECS_DOTNET_HOSTFXR` override does not point at a file.
    #[message("ECS_DOTNET_HOSTFXR does not point at a file: ", name_style(path))]
    HostfxrOverrideNotAFile { path: String },

    /// The selected hostfxr library could not be loaded.
    #[message("failed to load hostfxr from ", name_style(path))]
    HostfxrLoadFailed {
        path: String,
        #[source]
        source: libloading::Error,
    },

    /// The NativeAOT library could not be found on disk.
    #[message("no NativeAOT library at ", name_style(path))]
    AotLibraryNotFound { path: String },

    /// The NativeAOT library could not be loaded.
    #[message("failed to load NativeAOT library from ", name_style(path))]
    AotLibraryLoadFailed {
        path: String,
        #[source]
        source: libloading::Error,
    },

    /// A required export is missing from the NativeAOT library.
    #[message("failed to resolve NativeAOT export ", name_style(symbol))]
    AotExportMissing {
        symbol: String,
        #[source]
        source: libloading::Error,
    },

    /// A required hostfxr export is missing.
    #[message("failed to resolve hostfxr export ", name_style(symbol))]
    HostfxrExportMissing {
        symbol: String,
        #[source]
        source: libloading::Error,
    },

    /// Runtime initialization failed with a negative hostfxr status.
    #[message("hostfxr_initialize_for_runtime_config failed with ", value(status))]
    RuntimeInitializationFailed { status: String },

    /// The runtime delegate request failed with a negative hostfxr status.
    #[message("hostfxr_get_runtime_delegate failed with ", value(status))]
    RuntimeDelegateFailed { status: String },

    /// The managed export type is not a pointer-sized function pointer.
    #[message("managed export type is not pointer-sized")]
    ManagedExportNotPointerSized,

    /// A managed entry point could not be resolved or returned no pointer.
    #[message(
        "load_assembly_and_get_function_pointer failed for ",
        name_style(method),
        " with ",
        value(status)
    )]
    ManagedEntryPointFailed { method: String, status: String },

    /// The managed loader rejected host initialization.
    #[message("csharp_runtime initialization failed")]
    RuntimeInitFailed,

    /// The host-side C# mirror codegen step failed.
    #[message("C# component mirror generation failed: ", value(message))]
    CodegenFailed { message: String },

    /// The managed runtime was built for a different ABI contract version.
    #[message(
        "csharp_runtime interop version mismatch: host expects ",
        value(expected),
        " but the runtime reports ",
        value(actual)
    )]
    #[diagnostic(help("rebuild csharp_runtime and the host together"))]
    InteropVersionMismatch { expected: u32, actual: u32 },

    /// The managed-reported manifest length lies outside the supported range.
    #[message(
        "component manifest length ",
        value(length),
        " is outside the supported range (1..=",
        value(limit),
        ")"
    )]
    ManifestLengthOutOfRange { length: u32, limit: u32 },

    /// The manifest buffer could not be allocated.
    #[message("out of memory allocating the component manifest buffer")]
    ManifestAllocationFailed,

    /// The manifest copy from the managed runtime failed.
    #[message("failed to copy the component manifest from the managed runtime")]
    ManifestCopyFailed,

    /// The managed component manifest failed host-side JSON parsing.
    #[message("failed to parse the component manifest JSON")]
    ManifestParseFailed {
        #[source]
        source: serde_json::Error,
    },

    /// The managed component manifest failed host-side validation.
    #[message("invalid component manifest: ", value(message))]
    ManifestInvalid { message: String },

    /// A reflected managed startup method failed.
    #[message("startup method ", value(index), " failed")]
    StartupFailed { index: u32 },

    /// Queued startup commands failed to apply.
    #[message("startup commands failed: ", value(details))]
    StartupCommandsFailed { details: String },

    /// The managed assembly contains no schedulable systems.
    #[message("project_cs contains no [EcsSystem] methods")]
    NoSystems,

    /// The managed runtime refused to copy one system access declaration.
    #[message(
        "failed to get access ",
        value(access),
        " for C# system ",
        value(system)
    )]
    SystemAccessFailed { system: u32, access: u32 },

    /// A reflected access mode is neither read nor write.
    #[message("unknown C# access mode ", value(mode))]
    UnknownAccessMode { mode: u8 },

    /// A reflected access references a component the host never registered.
    #[message("C# system references unregistered component key ", value(key))]
    UnregisteredComponent { key: String },

    /// A managed string passed to hostfxr contains an interior NUL.
    #[message(".NET host string contains an interior NUL")]
    InteriorNul,
}

impl From<String> for CSharpError {
    /// Route free-form manifest validation messages into the typed
    /// `ManifestInvalid` variant.
    fn from(message: String) -> Self {
        Self::ManifestInvalid { message }
    }
}

impl From<serde_json::Error> for CSharpError {
    /// Preserve the real JSON parse error instead of converting it to text.
    fn from(source: serde_json::Error) -> Self {
        Self::ManifestParseFailed { source }
    }
}


// =============================================================================
// Host Error Composition
// =============================================================================

/// Transparent composition of every host subsystem error.
///
/// Subsystem functions return their narrowest meaningful error; [`HostError`]
/// exists only as the composition boundary where `?` crosses subsystems.
#[engine_error(namespace = host)]
pub enum HostError {
    /// Configuration validation failed.
    #[transparent]
    Config(#[from] ConfigError),

    /// The project-module build failed.
    #[transparent]
    Build(#[from] BuildError),

    /// Native library loading or initialization failed.
    #[transparent]
    Library(#[from] LibraryError),

    /// The source watcher could not start.
    #[transparent]
    Watcher(#[from] WatcherError),

    /// An optional module failed to load or is incompatible.
    #[transparent]
    Module(#[from] ModuleError),

    /// The managed backend failed to start.
    #[transparent]
    CSharp(#[from] CSharpError),

    /// The workspace root cannot be derived from the manifest directory.
    #[message("cannot determine the workspace root")]
    WorkspaceRootUndetermined,
}

// =============================================================================
// Free Functions
// =============================================================================

/// Install the engine report handler as miette's process-wide hook.
///
/// Call once at the top-level reporting boundary, before any report is
/// printed.
pub fn install_engine_report_handler() {
    // Install a hook that wraps every reported diagnostic in the styled proxy.
    let _ = miette::set_hook(Box::new(
        |_error: &(dyn miette::Diagnostic + 'static)| -> Box<dyn miette::ReportHandler> {
            Box::new(EngineReportHandler::default())
        },
    ));
}

/// Convert one engine error into a miette report with semantic styling.
///
/// This is the only error-handling call an executable boundary needs.
pub fn engine_report<E>(error: E) -> miette::Report
where
    E: EngineMessage + miette::Diagnostic + Send + Sync + 'static,
{
    miette::Report::new(StyledDiagnosticProxy::new(error))
}

// =============================================================================
// Tests
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use miette::Diagnostic as _;

    /// One rendered semantic fragment, recorded for verification.
    #[derive(Debug, PartialEq, Eq)]
    enum RecordedPart {
        Text(String),
        Styled { role: SemanticRole, text: String },
        Value(String),
        DebugValue(String),
    }

    /// Renderer that records calls instead of writing anywhere.
    struct RecordingRenderer {
        parts: Vec<RecordedPart>,
    }

    impl MessageRenderer for RecordingRenderer {
        fn text(&mut self, text: &str) -> fmt::Result {
            self.parts.push(RecordedPart::Text(text.to_string()));
            Ok(())
        }

        fn styled(&mut self, role: SemanticRole, value: &dyn fmt::Display) -> fmt::Result {
            self.parts.push(RecordedPart::Styled {
                role,
                text: value.to_string(),
            });
            Ok(())
        }

        fn value(&mut self, value: &dyn fmt::Display) -> fmt::Result {
            self.parts.push(RecordedPart::Value(value.to_string()));
            Ok(())
        }

        fn debug_value(&mut self, value: &dyn fmt::Debug) -> fmt::Result {
            self.parts
                .push(RecordedPart::DebugValue(format!("{value:?}")));
            Ok(())
        }
    }

    /// Plain rendering drops semantic roles and preserves values.
    #[test]
    fn plain_renderer_ignores_roles_and_keeps_values() {
        let error = BuildError::TimedOut {
            name: "project-rs".to_string(),
            seconds: 120,
        };
        assert_eq!(
            error.to_plain_message(),
            "build command for project-rs timed out after 120 seconds"
        );
    }

    /// Semantic rendering exposes the declared roles to the renderer.
    #[test]
    fn recording_renderer_sees_the_semantic_roles() {
        let error = CSharpError::InteropVersionMismatch {
            expected: 2,
            actual: 3,
        };
        let mut renderer = RecordingRenderer { parts: Vec::new() };
        error.render_message(&mut renderer).unwrap();
        assert_eq!(
            renderer.parts,
            vec![
                RecordedPart::Text(
                    "csharp_runtime interop version mismatch: host expects ".to_string()
                ),
                RecordedPart::Value("2".to_string()),
                RecordedPart::Text(" but the runtime reports ".to_string()),
                RecordedPart::Value("3".to_string()),
            ]
        );
    }

    /// Styled static tokens carry their role into the renderer.
    #[test]
    fn styled_static_tokens_carry_their_role() {
        let error = BuildError::OutputMissing {
            path: "target/debug/project.dll".to_string(),
        };
        let mut renderer = RecordingRenderer { parts: Vec::new() };
        error.render_message(&mut renderer).unwrap();
        assert_eq!(
            renderer.parts,
            vec![
                RecordedPart::Text("shared library not found at expected path: ".to_string()),
                RecordedPart::Styled {
                    role: SemanticRole::Name,
                    text: "target/debug/project.dll".to_string(),
                },
            ]
        );
    }

    /// Transparent composition preserves the plain message of the leaf error.
    #[test]
    fn transparent_composition_keeps_the_leaf_message() {
        let build = BuildError::Cancelled;
        let host_error: HostError = build.into();
        assert_eq!(
            host_error.to_string(),
            "build cancelled: sources changed again during compilation"
        );
        assert_eq!(
            host_error.to_plain_message(),
            "build cancelled: sources changed again during compilation"
        );
    }

    /// Real source errors remain stored as `#[source]`, not converted text.
    #[test]
    fn source_chain_preserves_the_underlying_error() {
        let source = std::io::Error::new(std::io::ErrorKind::NotFound, "missing program");
        let error = BuildError::SpawnFailed {
            name: "project-rs".to_string(),
            source,
        };
        assert!(std::error::Error::source(&error).is_some());
        let host_error: HostError = error.into();
        assert!(std::error::Error::source(&host_error).is_some());
    }

    /// Diagnostic codes derive from the namespace and variant name.
    #[test]
    fn diagnostic_codes_derive_from_namespace_and_variant() {
        let error = BuildError::Cancelled;
        assert_eq!(
            error.code().map(|code| code.to_string()).as_deref(),
            Some("host::build::cancelled")
        );
    }

    /// The terminal renderer applies name styling, visible even without
    /// ANSI assertions, through the quoting convention.
    #[test]
    fn terminal_renderer_quotes_name_tokens() {
        let error = WatcherError::WatchDirectoryMissing {
            path: "project_rs/src".to_string(),
        };
        let mut output = String::new();
        let mut renderer = TerminalMessageRenderer::new(&mut output);
        error.render_message(&mut renderer).unwrap();
        assert!(output.contains("\"project_rs/src\""));
    }
}
