//! A small generational arena for values addressed by stable handles.
//!
//! # Responsibilities
//!
//! - Hand out `Copy` handles that name one slot each, so a caller can pass
//!   them around while the map keeps owning the values.
//! - Validate every access against the version a handle was issued at, so a
//!   handle to a removed value fails instead of aliasing whatever refills its
//!   slot.
//! - Provide [`define_slot_key!`] so a crate can stamp out its own handle types
//!   over the shared machinery rather than reimplementing the validation.
//!
//! # Design
//!
//! Slots carry the current version and handles carry the version they were
//! issued at; comparing the two is what turns a stale handle into a miss.
//! [`SlotMap`] stays generic over the key, so one implementation serves every
//! kind of resource a crate wants to address this way.
//!
//! This is deliberately not the engine's asset storage. `pill_engine` addresses
//! assets through per-type columns and its own handle, because assets are
//! registered by type and outlive a reload; a flat cache of built objects is a
//! different problem, and this is the smaller tool for it.

// Standard library
use std::{marker::PhantomData, num::NonZeroU32};

/// Index and version that together identify one incarnation of a slot.
///
/// A handle carries the `KeyData` it was issued with, and the slot stores its
/// own version; a lookup only succeeds while the two match. Reusing a slot
/// bumps its version, so a handle from before the reuse stops validating
/// rather than naming its successor.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct KeyData {
    /// Position of the slot in the map's backing vector.
    pub index: u32,
    /// Version the slot must still carry for the handle to validate.
    pub version: NonZeroU32,
}

/// A typed handle for one entry of a [`SlotMap`].
///
/// Implementations are thin wrappers over a [`KeyData`], so handles stay `Copy`
/// and never borrow the value; the wrapper type records which slot map the
/// handle may be used with.
pub trait SlotKey: Copy + Eq {
    /// Builds a handle from a raw slot index and the version the slot must
    /// still carry for the handle to validate.
    ///
    /// Called where a handle is reconstructed outside the map's own insert - a
    /// packed key carries the index and version a later frame rebuilds one from
    /// - and where a fresh map seeds a placeholder handle to overwrite.
    fn new(index: u32, version: NonZeroU32) -> Self;

    /// Returns the raw [`KeyData`] the map validates the handle against.
    fn data(self) -> KeyData;
}

/// Defines one typed handle over [`KeyData`], with its accessors and its
/// [`SlotKey`] impl.
///
/// Every handle a crate needs is the same wrapper, differing only in name and
/// in which slot map accepts it, so the type is stamped out rather than written
/// per resource.
///
/// # Examples
///
/// ```ignore
/// pill_core::define_slot_key!(MeshHandle);
/// ```
#[macro_export]
macro_rules! define_slot_key {
    ($name:ident) => {
        /// A typed handle for the slots of the map it was issued by.
        ///
        /// Generated by `define_slot_key!`; the wrapper type keeps handles
        /// from different maps apart.
        #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
        pub struct $name($crate::slot_map::KeyData);

        impl $name {
            /// Builds a handle from a raw slot index and the version the slot
            /// must still carry for the handle to validate.
            pub fn new(index: u32, version: ::core::num::NonZeroU32) -> Self {
                Self($crate::slot_map::KeyData { index, version })
            }

            /// Returns the raw key data the map validates the handle against.
            pub fn data(self) -> $crate::slot_map::KeyData {
                self.0
            }
        }

        impl $crate::slot_map::SlotKey for $name {
            fn new(index: u32, version: ::core::num::NonZeroU32) -> Self {
                Self::new(index, version)
            }

            fn data(self) -> $crate::slot_map::KeyData {
                self.data()
            }
        }
    };
}

/// One entry of a [`SlotMap`]: the version it currently carries, and the value
/// living in it, if any.
struct Slot<V> {
    version: NonZeroU32,
    value: Option<V>,
}

/// Generational slot arena that hands out typed [`SlotKey`] handles.
///
/// Removal bumps the slot's version, so replacing a value can never make an old
/// handle read the new one; freed slots are reused before the slot vector
/// grows.
pub struct SlotMap<K, V> {
    slots: Vec<Slot<V>>,
    free: Vec<u32>,
    marker: PhantomData<fn() -> K>,
}

impl<K: SlotKey, V> SlotMap<K, V> {
    /// Creates an empty map for key type `K`, with room for `capacity` values.
    ///
    /// The key is named in the method rather than inferred because nothing in
    /// the arguments constrains it.
    pub fn with_capacity_and_key(capacity: usize) -> Self {
        Self {
            slots: Vec::with_capacity(capacity),
            free: Vec::new(),
            marker: PhantomData,
        }
    }

    /// Inserts a value and returns the handle that names it.
    ///
    /// A freed slot is reused before the vector grows, keeping the version its
    /// removal left behind, so the returned handle never equals the one that
    /// freed the slot.
    pub fn insert(&mut self, value: V) -> K {
        if let Some(index) = self.free.pop() {
            let slot = &mut self.slots[index as usize];
            slot.value = Some(value);
            return K::new(index, slot.version);
        }
        let index = self.slots.len() as u32;
        let version = NonZeroU32::new(1).unwrap();
        self.slots.push(Slot {
            version,
            value: Some(value),
        });
        K::new(index, version)
    }

    /// Looks up the value a handle names, or `None` if the handle is stale.
    ///
    /// The slot's version must match the handle's, so a slot emptied or reused
    /// after the handle was issued reads as stale.
    pub fn get(&self, key: K) -> Option<&V> {
        let data = key.data();
        let slot = self.slots.get(data.index as usize)?;
        (slot.version == data.version)
            .then_some(slot.value.as_ref())
            .flatten()
    }

    /// Looks up the value a handle names for mutation.
    ///
    /// Validation is the same as [`get`](Self::get): a stale handle yields
    /// `None` instead of aliasing the value that inherited its slot.
    pub fn get_mut(&mut self, key: K) -> Option<&mut V> {
        let data = key.data();
        let slot = self.slots.get_mut(data.index as usize)?;
        (slot.version == data.version)
            .then_some(slot.value.as_mut())
            .flatten()
    }

    /// Take the value out of its slot, invalidating every handle to it.
    ///
    /// The slot is freed for reuse behind a bumped version, so a handle kept
    /// from before the removal can never name whatever refills it. At the
    /// version ceiling the slot is retired instead of wrapped, because a
    /// version that wrapped would validate handles issued before the last few
    /// removals - the same reasoning any generational handle relies on.
    pub fn remove(&mut self, key: K) -> Option<V> {
        let data = key.data();
        let slot = self.slots.get_mut(data.index as usize)?;
        if slot.version != data.version {
            return None;
        }
        let value = slot.value.take()?;
        let next = slot.version.get().saturating_add(1);
        slot.version = NonZeroU32::new(next).unwrap();
        if next < u32::MAX {
            self.free.push(data.index);
        }
        Some(value)
    }
}
