//! Typed error system shared by every Pill workspace crate, generated from
//! one semantic message definition per variant.
//!
//! # Responsibilities
//!
//! - Define the semantic rendering protocol ([`SemanticRole`],
//!   [`MessageRenderer`], [`EngineMessage`]) used by generated code.
//! - Provide the plain and terminal renderers plus the miette presentation
//!   adapter and report handler.
//! - Declare every subsystem error ([`ConfigError`], [`BuildError`],
//!   [`LibraryError`], [`WatcherError`], [`CSharpError`],
//!   [`RenderingError`]) and their transparent composition [`HostError`].
//!
//! # Design
//!
//! Every error variant carries a single `#[message(...)]` definition. The
//! `#[engine_error]` macro generates the plain `Display` message, a stable
//! `namespace::variant` diagnostic code, and an [`EngineMessage`]
//! implementation that renders the same definition with semantic roles.
//! Subsystem errors compose into [`HostError`] through transparent
//! `#[from]` wrappers, so `?` works across boundaries while the leaf error
//! and its source chain survive. Styling lives only in the renderers; error
//! definitions never import a styling crate.

// Standard library
use std::fmt;

// External crates
use colored::Colorize;
use pill_core_macros::engine_error;

// =============================================================================
// Semantic Rendering Protocol
// =============================================================================

/// Semantic role of one message token.
///
/// Roles describe meaning, never appearance. The renderer decides how each
/// role looks in its target environment.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SemanticRole {
    /// General engine objects: `Scene`, `Component`, `System`, `Resource`.
    General,
    /// Specific engine objects or types: `Texture`, `Surface`, `Handle`.
    Specific,
    /// Module-level concepts: `Engine`, `Renderer`, `Window`.
    Module,
    /// User or domain names: file paths, scene names, symbol names.
    Name,
}

/// Sink for one semantically rendered error message.
///
/// Generated `EngineMessage` implementations call this protocol directly;
/// no intermediate vector or reconstructed string is ever created.
pub trait MessageRenderer {
    /// Write one plain-text fragment.
    fn text(&mut self, text: &str) -> fmt::Result;

    /// Write one value under a semantic role.
    fn styled(&mut self, role: SemanticRole, value: &dyn fmt::Display) -> fmt::Result;

    /// Write one plain dynamic value.
    fn value(&mut self, value: &dyn fmt::Display) -> fmt::Result;

    /// Write the debug representation of one dynamic value.
    fn debug_value(&mut self, value: &dyn fmt::Debug) -> fmt::Result;
}

/// Rendering interface generated by `#[engine_error]` for every error enum.
pub trait EngineMessage {
    /// Render the single semantic message definition into `renderer`.
    fn render_message(&self, renderer: &mut dyn MessageRenderer) -> fmt::Result;

    /// Convenience rendering into the plain renderer, for logs and tests.
    fn to_plain_message(&self) -> String {
        let mut output = String::new();
        let mut renderer = PlainMessageRenderer {
            output: &mut output,
        };
        // Rendering into a String can never fail.
        let _ = self.render_message(&mut renderer);
        output
    }
}

/// Renderer that ignores semantic roles and keeps values verbatim.
///
/// Used by tests, logs, and any non-styled environment; every message
/// degrades cleanly to plain text.
pub struct PlainMessageRenderer<'a, W> {
    output: &'a mut W,
}

impl<W: fmt::Write> PlainMessageRenderer<'_, W> {
    /// Wrap a writer for plain rendering.
    pub fn new(output: &mut W) -> PlainMessageRenderer<'_, W> {
        PlainMessageRenderer { output }
    }
}

impl<W: fmt::Write> MessageRenderer for PlainMessageRenderer<'_, W> {
    fn text(&mut self, text: &str) -> fmt::Result {
        self.output.write_str(text)
    }

    fn styled(&mut self, _role: SemanticRole, value: &dyn fmt::Display) -> fmt::Result {
        write!(self.output, "{value}")
    }

    fn value(&mut self, value: &dyn fmt::Display) -> fmt::Result {
        write!(self.output, "{value}")
    }

    fn debug_value(&mut self, value: &dyn fmt::Debug) -> fmt::Result {
        write!(self.output, "{value:?}")
    }
}

/// Terminal renderer carrying the project's visual style per semantic role.
///
/// This module owns all terminal appearance decisions; error definitions
/// never reference colors or ANSI styling.
pub struct TerminalMessageRenderer<'a, W> {
    output: &'a mut W,
}

impl<W: fmt::Write> TerminalMessageRenderer<'_, W> {
    /// Wrap a writer for styled terminal rendering.
    pub fn new(output: &mut W) -> TerminalMessageRenderer<'_, W> {
        TerminalMessageRenderer { output }
    }
}

impl<W: fmt::Write> MessageRenderer for TerminalMessageRenderer<'_, W> {
    fn text(&mut self, text: &str) -> fmt::Result {
        self.output.write_str(text)
    }

    fn styled(&mut self, role: SemanticRole, value: &dyn fmt::Display) -> fmt::Result {
        let value = value.to_string();
        let styled = match role {
            SemanticRole::General => value.bright_cyan().to_string(),
            SemanticRole::Specific => value.truecolor(95, 210, 90).to_string(),
            SemanticRole::Module => value.truecolor(180, 25, 100).bold().to_string(),
            SemanticRole::Name => format!("\"{value}\"").truecolor(190, 220, 160).to_string(),
        };
        self.output.write_str(&styled)
    }

    fn value(&mut self, value: &dyn fmt::Display) -> fmt::Result {
        write!(self.output, "{value}")
    }

    fn debug_value(&mut self, value: &dyn fmt::Debug) -> fmt::Result {
        write!(self.output, "{value:?}")
    }
}

// =============================================================================
// Miette Presentation
// =============================================================================

/// Presentation-only proxy that renders an engine error's primary message
/// with semantic terminal styling while keeping its diagnostic metadata.
///
/// The original error's `Display` stays plain; this adapter is allowed to
/// produce styled output because it is the reporting boundary, not the
/// domain error itself.
pub struct StyledDiagnosticProxy<E> {
    inner: E,
}

impl<E> StyledDiagnosticProxy<E> {
    /// Wrap an engine error for styled terminal reporting.
    pub fn new(inner: E) -> Self {
        Self { inner }
    }

    /// Unwrap the original error.
    pub fn into_inner(self) -> E {
        self.inner
    }
}

impl<E> fmt::Display for StyledDiagnosticProxy<E>
where
    E: EngineMessage,
{
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        let mut buffer = String::new();
        {
            let mut renderer = TerminalMessageRenderer::new(&mut buffer);
            self.inner.render_message(&mut renderer)?;
        }
        formatter.write_str(&buffer)
    }
}

impl<E: fmt::Debug> fmt::Debug for StyledDiagnosticProxy<E> {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        fmt::Debug::fmt(&self.inner, formatter)
    }
}

impl<E> std::error::Error for StyledDiagnosticProxy<E>
where
    E: EngineMessage + miette::Diagnostic,
{
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        self.inner.source()
    }
}

impl<E> miette::Diagnostic for StyledDiagnosticProxy<E>
where
    E: EngineMessage + miette::Diagnostic,
{
    fn code<'a>(&'a self) -> Option<Box<dyn fmt::Display + 'a>> {
        self.inner.code()
    }

    fn severity(&self) -> Option<miette::Severity> {
        self.inner.severity()
    }

    fn help<'a>(&'a self) -> Option<Box<dyn fmt::Display + 'a>> {
        self.inner.help()
    }

    fn url<'a>(&'a self) -> Option<Box<dyn fmt::Display + 'a>> {
        self.inner.url()
    }

    fn source_code(&self) -> Option<&dyn miette::SourceCode> {
        self.inner.source_code()
    }

    fn labels(&self) -> Option<Box<dyn Iterator<Item = miette::LabeledSpan> + '_>> {
        self.inner.labels()
    }

    fn related<'a>(&'a self) -> Option<Box<dyn Iterator<Item = &'a dyn miette::Diagnostic> + 'a>> {
        self.inner.related()
    }

    fn diagnostic_source(&self) -> Option<&dyn miette::Diagnostic> {
        self.inner.diagnostic_source()
    }
}

/// Terminal-aware report handler combining the engine semantic message with
/// miette's diagnostic metadata.
///
/// Stage A renders the semantic primary message through
/// [`StyledDiagnosticProxy`] and keeps miette's graphical rendering for
/// codes, help, sources, and cause chains.
#[derive(Debug)]
pub struct EngineReportHandler {
    inner: miette::GraphicalReportHandler,
}

impl Default for EngineReportHandler {
    fn default() -> Self {
        Self {
            inner: miette::GraphicalReportHandler::new(),
        }
    }
}

impl miette::ReportHandler for EngineReportHandler {
    fn debug(
        &self,
        error: &dyn miette::Diagnostic,
        formatter: &mut fmt::Formatter<'_>,
    ) -> fmt::Result {
        self.inner.debug(error, formatter)
    }
}

/// Install the engine report handler as miette's process-wide hook.
///
/// Call once at the top-level reporting boundary, before any report is
/// printed.
pub fn install_engine_report_handler() {
    let _ = miette::set_hook(Box::new(
        |_error: &(dyn miette::Diagnostic + 'static)| -> Box<dyn miette::ReportHandler> {
            Box::new(EngineReportHandler::default())
        },
    ));
}

/// Convert one engine error into a miette report with semantic styling.
///
/// This is the only error-handling call an executable boundary needs.
pub fn engine_report<E>(error: E) -> miette::Report
where
    E: EngineMessage + miette::Diagnostic + Send + Sync + 'static,
{
    miette::Report::new(StyledDiagnosticProxy::new(error))
}

// =============================================================================
// Subsystem Errors
// =============================================================================

/// Configuration-validation failures for game-module setups.
#[engine_error(namespace = host::config)]
pub enum ConfigError {
    /// The configured module name is empty.
    #[message("module name must not be empty")]
    EmptyModuleName,

    /// The configured watch directory is empty.
    #[message("watch directory must not be empty")]
    EmptyWatchDirectory,

    /// The configured build command is empty.
    #[message("build command must not be empty")]
    EmptyBuildCommand,
}

/// Game-module build execution failures.
#[engine_error(namespace = host::build)]
pub enum BuildError {
    /// The build command list is empty.
    #[message("build command must not be empty")]
    EmptyCommand,

    /// The build executable could not be spawned.
    #[message("failed to spawn build command for ", name_style(name))]
    SpawnFailed {
        name: String,
        #[source]
        source: std::io::Error,
    },

    /// The build child could not be waited on.
    #[message("failed to wait for the build command of ", name_style(name))]
    WaitFailed {
        name: String,
        #[source]
        source: std::io::Error,
    },

    /// The build command exited with a non-zero status.
    #[message(
        "build command failed for ",
        name_style(name),
        " with status ",
        value(status)
    )]
    CommandFailed {
        name: String,
        status: std::process::ExitStatus,
    },

    /// The build command exceeded its wall-clock deadline.
    #[message(
        "build command for ",
        name_style(name),
        " timed out after ",
        value(seconds),
        " seconds"
    )]
    TimedOut { name: String, seconds: u64 },

    /// Sources changed again while the build was running.
    #[message("build cancelled: sources changed again during compilation")]
    Cancelled,

    /// The build succeeded but no artifact appeared at the configured path.
    #[message("shared library not found at expected path: ", name_style(path))]
    #[diagnostic(help("check the selected backend output directory in GameModuleConfig"))]
    OutputMissing { path: String },
}

/// Native game-library loading and initialization failures.
#[engine_error(namespace = host::library)]
pub enum LibraryError {
    /// The per-process temporary directory could not be created.
    #[message(
        "failed to prepare temporary library directory ",
        name_style(directory)
    )]
    TemporaryDirectory {
        directory: String,
        #[source]
        source: std::io::Error,
    },

    /// The built library could not be copied to its temporary path.
    #[message(
        "failed to copy built library ",
        name_style(source_path),
        " to ",
        name_style(target_path)
    )]
    CopyFailed {
        source_path: String,
        target_path: String,
        #[source]
        source: std::io::Error,
    },

    /// The temporary copy is not a loadable native library.
    #[message("failed to load native game library from ", name_style(path))]
    LoadFailed {
        path: String,
        #[source]
        source: libloading::Error,
    },

    /// The library does not export a required entry point.
    #[message("native game library is missing required export ", name_style(symbol))]
    MissingExport {
        symbol: String,
        #[source]
        source: libloading::Error,
    },

    /// `game_init` reported a failed generation.
    #[message("game module initialization failed with status ", value(status))]
    InitializationFailed { status: u32 },
}

/// Source-watching startup failures.
#[engine_error(namespace = host::watcher)]
pub enum WatcherError {
    /// The configured watch directory does not exist.
    #[message("watch directory does not exist: ", name_style(path))]
    WatchDirectoryMissing { path: String },

    /// The platform file watcher could not be created.
    #[message("failed to create file watcher")]
    CreationFailed {
        #[source]
        source: notify::Error,
    },

    /// The watch path could not be registered.
    #[message("failed to register watch path ", name_style(path))]
    RegistrationFailed {
        path: String,
        #[source]
        source: notify::Error,
    },
}

/// Managed (C#) backend startup and registration failures.
#[engine_error(namespace = host::csharp)]
pub enum CSharpError {
    /// No hostfxr installation was found in any configured dotnet root.
    #[message("no .NET hostfxr installation found; searched the configured dotnet roots")]
    HostfxrNotFound,

    /// The `ECS_DOTNET_HOSTFXR` override does not point at a file.
    #[message("ECS_DOTNET_HOSTFXR does not point at a file: ", name_style(path))]
    HostfxrOverrideNotAFile { path: String },

    /// The selected hostfxr library could not be loaded.
    #[message("failed to load hostfxr from ", name_style(path))]
    HostfxrLoadFailed {
        path: String,
        #[source]
        source: libloading::Error,
    },

    /// A required hostfxr export is missing.
    #[message("failed to resolve hostfxr export ", name_style(symbol))]
    HostfxrExportMissing {
        symbol: String,
        #[source]
        source: libloading::Error,
    },

    /// Runtime initialization failed with a negative hostfxr status.
    #[message("hostfxr_initialize_for_runtime_config failed with ", value(status))]
    RuntimeInitializationFailed { status: String },

    /// The runtime delegate request failed with a negative hostfxr status.
    #[message("hostfxr_get_runtime_delegate failed with ", value(status))]
    RuntimeDelegateFailed { status: String },

    /// The managed export type is not a pointer-sized function pointer.
    #[message("managed export type is not pointer-sized")]
    ManagedExportNotPointerSized,

    /// A managed entry point could not be resolved or returned no pointer.
    #[message(
        "load_assembly_and_get_function_pointer failed for ",
        name_style(method),
        " with ",
        value(status)
    )]
    ManagedEntryPointFailed { method: String, status: String },

    /// The managed loader rejected host initialization.
    #[message("csharp_runtime initialization failed")]
    RuntimeInitFailed,

    /// The managed runtime was built for a different ABI contract version.
    #[message(
        "csharp_runtime interop version mismatch: host expects ",
        value(expected),
        " but the runtime reports ",
        value(actual)
    )]
    #[diagnostic(help("rebuild csharp_runtime and the host together"))]
    InteropVersionMismatch { expected: u32, actual: u32 },

    /// The managed-reported manifest length lies outside the supported range.
    #[message(
        "component manifest length ",
        value(length),
        " is outside the supported range (1..=",
        value(limit),
        ")"
    )]
    ManifestLengthOutOfRange { length: u32, limit: u32 },

    /// The manifest buffer could not be allocated.
    #[message("out of memory allocating the component manifest buffer")]
    ManifestAllocationFailed,

    /// The manifest copy from the managed runtime failed.
    #[message("failed to copy the component manifest from the managed runtime")]
    ManifestCopyFailed,

    /// The managed component manifest failed host-side JSON parsing.
    #[message("failed to parse the component manifest JSON")]
    ManifestParseFailed {
        #[source]
        source: serde_json::Error,
    },

    /// The managed component manifest failed host-side validation.
    #[message("invalid component manifest: ", value(message))]
    ManifestInvalid { message: String },

    /// A reflected managed startup method failed.
    #[message("startup method ", value(index), " failed")]
    StartupFailed { index: u32 },

    /// Queued startup commands failed to apply.
    #[message("startup commands failed: ", value(details))]
    StartupCommandsFailed { details: String },

    /// The managed assembly contains no schedulable systems.
    #[message("game_cs contains no [EcsSystem] methods")]
    NoSystems,

    /// The managed runtime refused to copy one system access declaration.
    #[message(
        "failed to get access ",
        value(access),
        " for C# system ",
        value(system)
    )]
    SystemAccessFailed { system: u32, access: u32 },

    /// A reflected access mode is neither read nor write.
    #[message("unknown C# access mode ", value(mode))]
    UnknownAccessMode { mode: u8 },

    /// A reflected access references a component the host never registered.
    #[message("C# system references unregistered component key ", value(key))]
    UnregisteredComponent { key: String },

    /// A managed string passed to hostfxr contains an interior NUL.
    #[message(".NET host string contains an interior NUL")]
    InteriorNul,
}

impl From<String> for CSharpError {
    /// Route free-form manifest validation messages into the typed
    /// `ManifestInvalid` variant.
    fn from(message: String) -> Self {
        Self::ManifestInvalid { message }
    }
}

impl From<serde_json::Error> for CSharpError {
    /// Preserve the real JSON parse error instead of converting it to text.
    fn from(source: serde_json::Error) -> Self {
        Self::ManifestParseFailed { source }
    }
}

/// Windowed-host rendering failures, compiled only with the `rendering`
/// feature.
#[cfg(feature = "rendering")]
#[engine_error(namespace = host::rendering)]
pub enum RenderingError {
    /// The engine renderer could not initialize against the window.
    #[message("engine renderer setup failed")]
    SetupFailed {
        #[source]
        source: pill_engine::RendererError,
    },

    /// The `winit` event loop could not be created.
    #[message("failed to create the event loop")]
    EventLoopCreation {
        #[source]
        source: winit::error::EventLoopError,
    },

    /// The native window could not be created.
    #[message("failed to create the standalone host window")]
    WindowCreation {
        #[source]
        source: winit::error::OsError,
    },
}

// =============================================================================
// Host Error Composition
// =============================================================================

/// Transparent composition of every host subsystem error.
///
/// Subsystem functions return their narrowest meaningful error; [`HostError`]
/// exists only as the composition boundary where `?` crosses subsystems.
#[engine_error(namespace = host)]
pub enum HostError {
    /// Configuration validation failed.
    #[transparent]
    Config(#[from] ConfigError),

    /// The game-module build failed.
    #[transparent]
    Build(#[from] BuildError),

    /// Native library loading or initialization failed.
    #[transparent]
    Library(#[from] LibraryError),

    /// The source watcher could not start.
    #[transparent]
    Watcher(#[from] WatcherError),

    /// The managed backend failed to start.
    #[transparent]
    CSharp(#[from] CSharpError),

    /// The windowed host failed to set up rendering.
    #[cfg(feature = "rendering")]
    #[transparent]
    Rendering(#[from] RenderingError),

    /// The workspace root cannot be derived from the manifest directory.
    #[message("cannot determine the workspace root")]
    WorkspaceRootUndetermined,
}

// =============================================================================
// Tests
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use miette::Diagnostic as _;

    /// One rendered semantic fragment, recorded for verification.
    #[derive(Debug, PartialEq, Eq)]
    enum RecordedPart {
        Text(String),
        Styled { role: SemanticRole, text: String },
        Value(String),
        DebugValue(String),
    }

    /// Renderer that records calls instead of writing anywhere.
    struct RecordingRenderer {
        parts: Vec<RecordedPart>,
    }

    impl MessageRenderer for RecordingRenderer {
        fn text(&mut self, text: &str) -> fmt::Result {
            self.parts.push(RecordedPart::Text(text.to_string()));
            Ok(())
        }

        fn styled(&mut self, role: SemanticRole, value: &dyn fmt::Display) -> fmt::Result {
            self.parts.push(RecordedPart::Styled {
                role,
                text: value.to_string(),
            });
            Ok(())
        }

        fn value(&mut self, value: &dyn fmt::Display) -> fmt::Result {
            self.parts.push(RecordedPart::Value(value.to_string()));
            Ok(())
        }

        fn debug_value(&mut self, value: &dyn fmt::Debug) -> fmt::Result {
            self.parts
                .push(RecordedPart::DebugValue(format!("{value:?}")));
            Ok(())
        }
    }

    /// Plain rendering drops semantic roles and preserves values.
    #[test]
    fn plain_renderer_ignores_roles_and_keeps_values() {
        let error = BuildError::TimedOut {
            name: "game-rs".to_string(),
            seconds: 120,
        };
        assert_eq!(
            error.to_plain_message(),
            "build command for game-rs timed out after 120 seconds"
        );
    }

    /// Semantic rendering exposes the declared roles to the renderer.
    #[test]
    fn recording_renderer_sees_the_semantic_roles() {
        let error = CSharpError::InteropVersionMismatch {
            expected: 2,
            actual: 3,
        };
        let mut renderer = RecordingRenderer { parts: Vec::new() };
        error.render_message(&mut renderer).unwrap();
        assert_eq!(
            renderer.parts,
            vec![
                RecordedPart::Text(
                    "csharp_runtime interop version mismatch: host expects ".to_string()
                ),
                RecordedPart::Value("2".to_string()),
                RecordedPart::Text(" but the runtime reports ".to_string()),
                RecordedPart::Value("3".to_string()),
            ]
        );
    }

    /// Styled static tokens carry their role into the renderer.
    #[test]
    fn styled_static_tokens_carry_their_role() {
        let error = BuildError::OutputMissing {
            path: "target/debug/game.dll".to_string(),
        };
        let mut renderer = RecordingRenderer { parts: Vec::new() };
        error.render_message(&mut renderer).unwrap();
        assert_eq!(
            renderer.parts,
            vec![
                RecordedPart::Text("shared library not found at expected path: ".to_string()),
                RecordedPart::Styled {
                    role: SemanticRole::Name,
                    text: "target/debug/game.dll".to_string(),
                },
            ]
        );
    }

    /// Transparent composition preserves the plain message of the leaf error.
    #[test]
    fn transparent_composition_keeps_the_leaf_message() {
        let build = BuildError::Cancelled;
        let host_error: HostError = build.into();
        assert_eq!(
            host_error.to_string(),
            "build cancelled: sources changed again during compilation"
        );
        assert_eq!(
            host_error.to_plain_message(),
            "build cancelled: sources changed again during compilation"
        );
    }

    /// Real source errors remain stored as `#[source]`, not converted text.
    #[test]
    fn source_chain_preserves_the_underlying_error() {
        let source = std::io::Error::new(std::io::ErrorKind::NotFound, "missing program");
        let error = BuildError::SpawnFailed {
            name: "game-rs".to_string(),
            source,
        };
        assert!(std::error::Error::source(&error).is_some());
        let host_error: HostError = error.into();
        assert!(std::error::Error::source(&host_error).is_some());
    }

    /// Diagnostic codes derive from the namespace and variant name.
    #[test]
    fn diagnostic_codes_derive_from_namespace_and_variant() {
        let error = BuildError::Cancelled;
        assert_eq!(
            error.code().map(|code| code.to_string()).as_deref(),
            Some("host::build::cancelled")
        );
    }

    /// The terminal renderer applies name styling, visible even without
    /// ANSI assertions, through the quoting convention.
    #[test]
    fn terminal_renderer_quotes_name_tokens() {
        let error = WatcherError::WatchDirectoryMissing {
            path: "game_rs/src".to_string(),
        };
        let mut output = String::new();
        let mut renderer = TerminalMessageRenderer::new(&mut output);
        error.render_message(&mut renderer).unwrap();
        assert!(output.contains("\"game_rs/src\""));
    }
}
