[package]
name = "project"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
pill_engine = { path = "../engine" }
pill_core = { path = "../pill_core" }
trait_type_map = { path = "../../Trait-Type-Map" }
serde = { version = "1", features = ["derive"] }
tracing = "0.1"

[features]
rendering = ["pill_engine/rendering"]
