//! Hot-reloadable bouncing-ball project implemented with ECS systems.
//!
//! # Responsibilities
//!
//! - Runs the ball physics: [`BALL_COUNT`] balls bouncing inside a fixed box,
//!   stepped by the frame delta the host clock reports.
//! - Drives the project's single [`Spline`]: its control points are the ball
//!   centres, and one [`SplineSample`] dot sits on the curve every
//!   [`SPLINE_SAMPLE_STEP`] of `t`.
//! - Exposes `pill_module_init`, the entry point the host resolves in this
//!   artifact through the project-module ABI (generated by `#[pill_project]`).
//!
//! # Design
//!
//! The project is a plain `cdylib` that registers ECS components, resources,
//! and systems during `pill_module_init`, against the engine the host hands it
//! through [`EngineApi`]. Hot reload
//! preserves entities, so initialization fills the world only up to the target
//! counts instead of spawning fresh entities on every rebuild.
//!
//! Balls and spline are tied together by data rather than by an entity
//! relationship: `spline_path_system` copies the ball centres into the control
//! point array on every frame, which keeps every component in the scene plain,
//! serializable data.

// Standard library
use std::time::Instant;

// External crates
use pill_core::error;
use pill_core::math::Vector3f;
use pill_engine::*;
// `Position` is the engine's: it is universal, so a project
// names them without reaching through whichever renderer happens to draw them.
// `MeshRendererComponent` is the renderer's own idea of a thing to draw.
use pill_engine::common_components::Position;
use pill_master_renderer::{
    CameraComponent, DirectionalLightComponent, Material, Mesh, MeshRendererComponent,
    TransformComponent,
};
use pill_spline::Spline;
use serde::{Deserialize, Serialize};

mod audio_scene;
mod physics;
// Hot patches compile separately and import the same scene settings.
pub mod settings;
mod simulation_time;
mod spline_path;
mod spline_probe;

// Keep the public hot-patch helper available at its original crate-root path.
pub use physics::simulate_ball;

use physics::{ball_spawn_state, physics_system};
use settings::*;
use simulation_time::update_time_system;
use spline_path::spline_path_system;
use spline_probe::{spline_probe_system, SplineProbeState};

/// Wall-clock delta between frames, shared by every system that steps on time.
///
/// Public so a hot patch can name it: a patched system's signature must be
/// expressible from outside the crate.
pub struct SimulationTime {
    pub last_frame: Instant,
    pub delta_seconds: f32,

    pub test: i32,
}

impl Resource for SimulationTime {}

/// A rigid ball that bounces inside a fixed box, simulated each frame.
///
/// The host serializes this component across hot-reload generations, so the
/// struct layout is pinned with `#[repr(C)]` and every field stays
/// `Serialize` / `Deserialize` compatible.
#[repr(C)]
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PillComponent)]
#[pill(persistable)]
pub struct PhysicsState {
    pub delta_time: f32,
    pub position_x: f32,
    pub position_y: f32,
    pub velocity_x: f32,
    pub velocity_y: f32,
    pub radius: f32,
    pub active: bool,
}

/// One dot on the project's spline, drawn at the curve parameter `t`.
///
/// The dot carries the usual [`Position`] and [`MeshRendererComponent`], so it renders like
/// any other mesh, and `spline_path_system` moves it along the curve as the
/// balls move. The host serializes this component across hot-reload
/// generations, so the layout is pinned with `#[repr(C)]`.
#[repr(C)]
#[derive(Debug, Clone, Copy, Default, Serialize, Deserialize, PillComponent)]
#[pill(persistable)]
pub struct SplineSample {
    /// Curve parameter this dot samples, running from 0.0 to 1.0.
    pub t: f32,
}

/// Registers resources and systems; component registration happens
/// automatically from the `PillComponent` derives before this runs.
///
/// The host treats a non-zero status as a failed generation and rolls back to
/// the previously loaded module. Initialization must therefore be idempotent:
/// re-registering the same resources and systems is safe, and entities are
/// only filled up to a target count.
///
/// Public so a statically linked build can call it directly. With a reloading
/// build, `#[pill_project]` also exports it as `pill_module_init` for the host to
/// resolve in the loaded DLL.
#[pill_project]
pub fn init(engine: &mut Engine) -> u32 {
    // Register the renderer from the project artifact so its extraction system
    // uses the same concrete asset types as this DLL. RenderFrame is a shared
    // resource, so the host-side GPU backend reads the extracted data through
    // the engine's stable cross-artifact resource identity.
    pill_master_renderer::register(engine);
    let (mesh, scene_material, ball_materials, sample_material) = {
        let assets = engine
            .world_mut()
            .get_resource_mut::<AssetManager>()
            .expect("Engine always owns an AssetManager");
        let mesh = assets
            .handle_by_name::<Mesh>("project.triangle")
            .unwrap_or_else(|| assets.add_named("project.triangle", Mesh::triangle()));
        let mut material = |name: &str, color: [f32; 3], specularity: f32| {
            assets.handle_by_name::<Material>(name).unwrap_or_else(|| {
                assets.add_named(
                    name,
                    Material::builder(name)
                        .color_parameter("tint", color)
                        .scalar_parameter("specularity", specularity)
                        .build(),
                )
            })
        };
        let scene_material = material("project.scene", [0.8, 0.8, 0.85], 0.5);
        let ball_materials: [Handle<Material>; BALL_COUNT] = std::array::from_fn(|index| {
            material(
                &format!("project.ball.{index}"),
                [BALL_COLOR.r, BALL_COLOR.g, BALL_COLOR.b],
                index as f32 / BALL_COUNT as f32,
            )
        });
        let sample_material = material(
            "project.spline",
            [SAMPLE_DOT_COLOR.r, SAMPLE_DOT_COLOR.g, SAMPLE_DOT_COLOR.b],
            0.2,
        );
        (mesh, scene_material, ball_materials, sample_material)
    };
    let has_camera = Query::<&CameraComponent>::new(engine.world_mut())
        .iter_mut()
        .next()
        .is_some();
    if !has_camera {
        if engine
            .world_mut()
            .create_entity()
            .with(TransformComponent::default())
            .with(DirectionalLightComponent::default())
            .build()
            .is_err()
        {
            return 1;
        }
        let renderable = MeshRendererComponent::builder()
            .mesh(&mesh)
            .material(&scene_material)
            .build();
        if engine
            .world_mut()
            .create_entity()
            .with(renderable)
            .with(TransformComponent {
                translation: [0.0, 0.0, -1.5],
                scale: [1.5; 3],
                ..Default::default()
            })
            .build()
            .is_err()
        {
            return 1;
        }
    }
    if !has_camera {
        if engine
            .world_mut()
            .create_entity()
            .with(CameraComponent::default())
            .with(TransformComponent {
                translation: [0.0, 0.0, 9.0],
                ..Default::default()
            })
            .build()
            .is_err()
        {
            return 1;
        }
    }

    if let Err(message) = audio_scene::initialize(engine) {
        eprintln!("[project] audio initialization failed: {message}");
        return 1;
    }

    engine.world_mut().insert_resource(SimulationTime {
        last_frame: Instant::now(),
        delta_seconds: FIXED_DELTA_TIME,
        test: 0,
    });
    engine.register_system("simulation_time", update_time_system);
    engine.register_system("ball_physics", physics_system);
    engine.register_system("spline_path", spline_path_system);
    engine.world_mut().insert_resource(SplineProbeState {
        last_report: Instant::now(),
    });
    engine.register_system("spline_probe", spline_probe_system);

    // The spline entity. `Spline` is registered by the linked `pill_spline`
    // crate, and the host may also be loading a separately built copy of that
    // crate as a module DLL. `Spline` declares `#[pill(shared)]`, so both
    // copies are one component with one column: this query sees the module's
    // spline as readily as the project's own, and whichever artifact
    // initialises first creates the entity while the other adopts it.
    //
    // `spline_path_system` rewrites the control points from the ball centres
    // every frame, so the only decision left here is whether the world already
    // has a spline: hot reload preserves entities, and a second one would be a
    // curve nobody asked for. A fresh one is seeded with the spawn positions,
    // so even the first frame shows a curve through the balls rather than
    // every sample dot stacked on the origin.
    let existing_spline = {
        let mut query = Query::<&Spline>::new(engine.world_mut());
        query.iter_mut().next().copied()
    };
    let spline = match existing_spline {
        Some(spline) => spline,
        None => {
            let mut spawn_points = [Vector3f::ZERO; BALL_COUNT];
            for (index, point) in spawn_points.iter_mut().enumerate() {
                let ball = ball_spawn_state(index);
                *point = Vector3f::new(ball.position_x, ball.position_y, 0.0);
            }
            let seeded = Spline::from_points(&spawn_points);
            if engine
                .world_mut()
                .create_entity()
                .with(seeded)
                .build()
                .is_err()
            {
                error!(
                    target: pill_core::telemetry::telemetry_target::ECS,
                    "failed to build the project spline entity; aborting this generation"
                );
                return 1;
            }
            seeded
        }
    };

    // Balls are filled up to `BALL_COUNT` rather than spawned fresh on every
    // rebuild, because hot reload keeps the entities that already exist.
    let existing_balls = {
        let mut query = Query::<&PhysicsState>::new(engine.world_mut());
        query.iter_mut().count()
    };
    for index in existing_balls..BALL_COUNT {
        let physics = ball_spawn_state(index);
        let entity = engine
            .world_mut()
            .create_entity()
            .with(physics)
            .with(Position {
                x: physics.position_x - physics.radius,
                y: physics.position_y - physics.radius,
            })
            .with(TransformComponent {
                translation: [
                    (physics.position_x - 400.0) / 80.0,
                    (300.0 - physics.position_y) / 80.0,
                    0.0,
                ],
                scale: [physics.radius / 80.0; 3],
                ..Default::default()
            })
            .with(
                MeshRendererComponent::builder()
                    .mesh(&mesh)
                    .material(&ball_materials[index])
                    .build(),
            );

        if entity.build().is_err() {
            // Report the failure and abort the generation: the host keeps the
            // previously loaded module when the init returns non-zero.
            error!(
                target: pill_core::telemetry::telemetry_target::ECS,
                "failed to build a ball entity; aborting this project generation"
            );
            return 1;
        }
    }

    // One sample dot per t step, placed on the curve as it stands right now:
    // the seeded spawn shape on a cold start, the live ball-driven curve after
    // a reload. Only the position is ever rewritten afterwards, so the
    // inspector can retune the dots' size and colour while the sim runs.
    let existing_samples = {
        let mut query = Query::<&SplineSample>::new(engine.world_mut());
        query.iter_mut().count()
    };
    for index in existing_samples..SPLINE_SAMPLE_COUNT {
        let t = index as f32 * SPLINE_SAMPLE_STEP;
        let location = spline.get_location_at(t);
        let entity = engine
            .world_mut()
            .create_entity()
            .with(SplineSample { t })
            .with(Position {
                x: location.x - SPLINE_SAMPLE_DOT_SIZE * 0.5,
                y: location.y - SPLINE_SAMPLE_DOT_SIZE * 0.5,
            })
            .with(TransformComponent {
                translation: [
                    (location.x - 400.0) / 80.0,
                    (300.0 - location.y) / 80.0,
                    0.0,
                ],
                scale: [SPLINE_SAMPLE_DOT_SIZE / 160.0; 3],
                ..Default::default()
            })
            .with(
                MeshRendererComponent::builder()
                    .mesh(&mesh)
                    .material(&sample_material)
                    .build(),
            );

        if entity.build().is_err() {
            error!(
                target: pill_core::telemetry::telemetry_target::ECS,
                "failed to build a spline sample dot; aborting this project generation"
            );
            return 1;
        }
    }

    // Report successful registration so the host keeps this generation.
    0
}
