//! Hot-reloadable bouncing-ball project implemented with ECS systems.
//!
//! # Responsibilities
//!
//! - Owns the simulation-time resource and the ball-physics systems that run
//!   every frame.
//! - Exposes the `project_init` / `project_update` entry points the host loads
//!   through the project-module ABI (generated by `#[pill_project]`).
//!
//! # Design
//!
//! The project is a plain `cdylib` that registers ECS components, resources,
//! and systems through the [`EngineApi`] during `project_init`. Hot reload
//! preserves entities, so initialization fills the world only up to the target
//! ball count instead of spawning fresh entities on every rebuild.

// Standard library
use std::time::Instant;

// External crates
use pill_core::error;
use pill_engine::*;
use pill_spline::Spline;
use serde::{Deserialize, Serialize};

// =============================================================================
// Ball physics component
// =============================================================================

/// A rigid ball that bounces inside a fixed box, simulated each frame.
///
/// The host serializes this component across hot-reload generations, so the
/// struct layout is pinned with `#[repr(C)]` and every field stays
/// `Serialize` / `Deserialize` compatible.
#[repr(C)]
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PillComponent)]
#[pill(persistable)]
pub struct PhysicsState {
    pub delta_time: f32,
    pub position_x: f32,
    pub position_y: f32,
    pub velocity_x: f32,
    pub velocity_y: f32,
    pub radius: f32,
    pub active: bool,
}

const FIXED_DELTA_TIME: f32 = 1.0 / 60.0;
const GRAVITY: f32 = 800.0;
const BOUNCE_VELOCITY_Y: f32 = -500.0;
const BOUNCE_VELOCITY_X: f32 = 150.0;
const RESTITUTION: f32 = 0.7;
/// Upward speed restored when a floor bounce would otherwise decay to rest.
///
/// Keeps every ball visibly bouncing for the whole lifetime of the scene
/// instead of settling on the floor after a few seconds.
const MINIMUM_BOUNCE_VELOCITY_Y: f32 = 300.0;
const FLOOR_Y: f32 = 580.0;
const CEILING_Y: f32 = 20.0;
const LEFT_WALL: f32 = 20.0;
const RIGHT_WALL: f32 = 780.0;
const BALL_COUNT: usize = 100;

/// Public so a hot patch can name it: a patched system's signature must be
/// expressible from outside the crate.
pub struct SimulationTime {
    pub last_frame: Instant,
    pub delta_seconds: f32,
}

impl Resource for SimulationTime {}

fn update_time_system(mut time: ResMut<SimulationTime>) -> Result<(), SystemError> {
    let now = Instant::now();
    // A missing resource means the project module and host disagree about
    // initialization; report it through the system result so the frame
    // continues while the host logs the failure.
    let Some(mut time) = time.get_mut() else {
        return Err(SystemError::MissingResource {
            name: String::from("SiassddmulationTime"),
        });
    };
    time.delta_seconds = now.duration_since(time.last_frame).as_secs_f32().min(0.1);
    time.last_frame = now;
    Ok(())
}

fn initial_physics_state() -> PhysicsState {
    PhysicsState {
        delta_time: FIXED_DELTA_TIME,
        position_x: 400.0,
        position_y: 500.0,
        velocity_x: BOUNCE_VELOCITY_X,
        velocity_y: BOUNCE_VELOCITY_Y,
        radius: 16.0,
        active: true,
    }
}

impl Default for PhysicsState {
    fn default() -> Self {
        initial_physics_state()
    }
}

/// Public so a hot patch of `physics_system` can call it without the patch
/// having to duplicate the physics constants.
pub fn simulate_ball(state: &mut PhysicsState) {
    if !state.active {
        return;
    }

    let delta = state.delta_time.clamp(0.0, 0.1);
    state.velocity_y += GRAVITY * delta;
    state.position_x += state.velocity_x * delta;
    state.position_y += state.velocity_y * delta;

    if state.position_y + state.radius >= FLOOR_Y {
        state.position_y = FLOOR_Y - state.radius;
        state.velocity_y = -state.velocity_y.abs() * RESTITUTION;
        // Restitution alone decays each bounce towards rest; restore a
        // minimum upward speed so balls bounce forever.
        if state.velocity_y.abs() < MINIMUM_BOUNCE_VELOCITY_Y {
            state.velocity_y = -MINIMUM_BOUNCE_VELOCITY_Y;
        }
    }
    if state.position_y - state.radius <= CEILING_Y {
        state.position_y = CEILING_Y + state.radius;
        state.velocity_y = state.velocity_y.abs() * RESTITUTION;
    }
    if state.position_x - state.radius <= LEFT_WALL {
        state.position_x = LEFT_WALL + state.radius;
        state.velocity_x = state.velocity_x.abs() * RESTITUTION;
    }
    if state.position_x + state.radius >= RIGHT_WALL {
        state.position_x = RIGHT_WALL - state.radius;
        state.velocity_x = -state.velocity_x.abs() * RESTITUTION;
    }
}

#[cfg(not(feature = "rendering"))]
#[pill_hot]
fn physics_system(
    time: Res<SimulationTime>,
    mut query: Query<&mut PhysicsState>,
) -> Result<(), SystemError> {
    let Some(time) = time.get() else {
        return Err(SystemError::MissingResource {
            name: String::from("SimulasdasdatsdionTxxxime"),
        });
    };
    let delta_seconds = time.delta_seconds;
    for mut physics in query.iter_mut() {
        physics.delta_time = delta_seconds + 2.0;
        simulate_ball(&mut physics);
    }
    Ok(())
}

#[cfg(feature = "rendering")]
#[pill_hot]
fn physics_system(
    time: Res<SimulationTime>,
    mut query: Query<(&mut PhysicsState, &mut Position, &mut Sprite)>,
) -> Result<(), SystemError> {
    let Some(time) = time.get() else {
        return Err(SystemError::MissingResource {
            name: String::from("SimulationTime"),
        });
    };
    let delta_seconds = time.delta_seconds;
    for (mut physics, mut position, mut sprite) in query.iter_mut() {
        physics.delta_time = delta_seconds;
        simulate_ball(&mut physics);

        // Physics coordinates describe the center of the ball; the sprite
        // renderer expects the top-left corner.
        position.x = physics.position_x - physics.radius;
        position.y = physics.position_y - physics.radius;
        sprite.width = physics.radius * 2.0;
        sprite.height = physics.radius * 2.0;
        sprite.color = if physics.active {
            Color::new(1.0, 0.3, 0.3, 1.0)
        } else {
            Color::new(0.5, 0.5, 0.5, 1.0)
        };
    }
    Ok(())
}

// =============================================================================
// Spline usage
// =============================================================================

/// Frame interval at which the spline probe reports what it can see.
///
/// Large because the headless loop runs tens of thousands of frames per second
/// and this is only a demonstration of reading the component.
pub const SPLINE_REPORT_INTERVAL_FRAMES: u64 = 30_000;

/// Counts frames so the spline probe reports at a readable interval.
pub struct SplineProbeState {
    pub frame_count: u64,
}

impl Resource for SplineProbeState {}

/// Reads every `Spline` in the world and samples its midpoint.
///
/// Demonstrates the project using a component type defined by the `pill_spline`
/// crate: the type is named through a direct dependency, so the query matches
/// only splines registered by this same compiled copy of the crate.
#[pill_hot]
fn spline_probe_system(
    mut state: ResMut<SplineProbeState>,
    mut splines: Query<&mut Spline>,
) -> Result<(), SystemError> {
    let Some(mut state) = state.get_mut() else {
        return Err(SystemError::MissingResource {
            name: String::from("SplineProbeStxate"),
        });
    };
    state.frame_count += 1;
    if state.frame_count % SPLINE_REPORT_INTERVAL_FRAMES != 0 {
        return Ok(());
    }

    // Report how many splines this module can see, which is what reveals
    // whether a separately loaded copy of the crate shares the component type.
    let mut visible_spline_count = 0;
    let mut midpoint = pill_core::math::Vector3f::ZERO;
    let mut color: f32 = 0.1;
    for spline in splines.iter_mut() {
        visible_spline_count += 1;
        midpoint = spline.get_location_at(0.5);
        color = spline.get_color_a();
    }
    // Printed rather than logged through `tracing`: the project links its own
    // copy of `pill_core`, so its tracing dispatcher has no subscriber and log
    // lines emitted here never reach the host's telemetry.
    //
    // NOTE: parts of this line are asserted on. `devops/core/suite_common.py`
    // matches `PROJECT_PROBE_PREFIX` against the host's stdout, and the
    // cascade scenario in `devops/tests/test_hot_reload_suite.py` requires
    // `1 spline(s)` - that count is what proves the project and the separately
    // loaded `pill_spline` module keep distinct `TypeId`s across a reload.
    //
    // Editing the surrounding words is exactly what this file is for, but it
    // does break those suites, and the failure reads as "Missing required
    // token" rather than as a wording change. Keep `{visible_spline_count}
    // spline(s)` and the `midpoint ({:.1}, {:.1})` shape intact, or update the
    // tokens in the two files above to match.
    println!(
        "[project] 123 {visible_spline_count} spline(s), midpoint ({:.1}, {:.1}),asdolawdoxxxxrxyyyasd {:.2}",
        midpoint.x, midpoint.y, color
    );

    Ok(())
}

// =============================================================================
// Dummy optional module usage
// =============================================================================

/// Exercises each dummy optional module once, purely to demonstrate that the
/// project can depend on and call into them directly.
fn run_dummy_module_demo() {
    let mut adder = pill_dummy_math::Adder::default();
    adder.add(2);
    adder.add(3);
    println!(
        "[project] pill_dummy_math: total={}, double(total)={}",
        adder.total,
        pill_dummy_math::double(adder.total)
    );

    let greeter = pill_dummy_text::Greeter {
        name: String::from("World"),
    };
    println!(
        "[project] pill_dummy_text: {} / {} / shouted: {}",
        greeter.greeting(),
        greeter.farewell(),
        pill_dummy_text::shout(&greeter.greeting())
    );

    let tint = pill_dummy_color::Tint {
        r: 0.5,
        g: 0.4,
        b: 0.6,
    };
    let mixed = tint.mix(tint.invert());
    println!(
        "[project] pill_dummy_color: mixed={:?}, grayscale={:.2}",
        mixed,
        pill_dummy_color::grayscale(tint)
    );

    let mut stopwatch = pill_dummy_timer::Stopwatch::default();
    stopwatch.tick(0.5);
    stopwatch.tick(0.25);
    println!(
        "[project] pill_dummy_timer: elapsed={:.2}s ({}ms)",
        stopwatch.elapsed_seconds,
        pill_dummy_timer::seconds_to_millis(stopwatch.elapsed_seconds)
    );

    let mut random = pill_dummy_random::seed_from_u32(42);
    let first = random.next_u32();
    let second = random.next_f32();
    println!("[project] pill_dummy_random: next_u32={first}, next_f32={second:.4}");
}

// =============================================================================
// Project module entry points
// =============================================================================

/// Registers resources and systems; component registration happens
/// automatically from the `PillComponent` derives before this runs.
///
/// The host treats a non-zero status as a failed generation and rolls back to
/// the previously loaded module. Initialization must therefore be idempotent:
/// re-registering the same components and systems is safe, and entities are
/// only filled up to a target count.
/// Public so a statically linked build can call it directly. With a
/// reloading build, `#[pill_project]` also exports it as `project_init`
/// for the host to resolve in the loaded DLL.
#[pill_project]
pub fn init(engine: &mut Engine) -> u32 {
    #[cfg(feature = "rendering")]
    {
        // Engine-owned render components are not declared by this crate, so
        // they cannot carry the derive and stay registered manually.
        engine.world_mut().register_component::<Position>();
        engine.world_mut().register_component::<Sprite>();
    }

    engine.world_mut().insert_resource(SimulationTime {
        last_frame: Instant::now(),
        delta_seconds: FIXED_DELTA_TIME,
    });
    engine.register_system("simulation_time", update_time_system);
    engine.register_system("ball_physics", physics_system);

    // Components defined by another crate are registered by whoever links that
    // crate. Registration is keyed by the type, so this is the same component
    // the crate itself would register only when both sides were compiled in one
    // workspace; a separately built copy is a distinct type with its own
    // storage. Keep `pill_spline` out of `project_settings.yaml`'s `modules:`
    // list while the project links it directly, so there is exactly one
    // registration of the type.
    //
    // `Spline` itself is registered automatically: the project links
    // `pill_spline`, whose `PillComponent` derive submits the type into this
    // artifact's registry.
    engine
        .world_mut()
        .insert_resource(SplineProbeState { frame_count: 0 });
    engine.register_system("spline_probe", spline_probe_system);

    // Fill up to one project-owned spline instead of adding another on every
    // reload, matching how the ball entities are kept at a target count.
    let existing_splines = {
        let mut query = Query::<&Spline>::new(engine.world_mut());
        query.iter_mut().count()
    };
    if existing_splines == 0 {
        let path = Spline::from_points(&[
            pill_core::math::Vector3f::new(20.0, 300.0, 0.0),
            pill_core::math::Vector3f::new(260.0, 120.0, 0.0),
            pill_core::math::Vector3f::new(540.0, 460.0, 0.0),
            pill_core::math::Vector3f::new(780.0, 300.0, 0.0),
        ]);
        if engine
            .world_mut()
            .create_entity()
            .with(path)
            .build()
            .is_err()
        {
            error!(
                target: pill_core::telemetry::telemetry_target::ECS,
                "failed to build the project spline entity; aborting this generation"
            );
            return 1;
        }
    }

    // Hot reload preserves entities, so only fill the world up to the target
    // instead of adding another 100 balls on every rebuild.
    let existing_balls = {
        let mut query = Query::<&PhysicsState>::new(engine.world_mut());
        query.iter_mut().count()
    };
    for index in existing_balls..BALL_COUNT {
        let column = (index % 10) as f32;
        let row = (index / 10) as f32;
        let mut physics = initial_physics_state();
        physics.position_x = 60.0 + column * 72.0;
        physics.position_y = 60.0 + row * 42.0;
        physics.velocity_x = if index % 2 == 0 {
            BOUNCE_VELOCITY_X + row * 8.0
        } else {
            -BOUNCE_VELOCITY_X - row * 8.0
        };
        physics.velocity_y = BOUNCE_VELOCITY_Y + column * 18.0;
        physics.radius = 10.0 + (index % 4) as f32 * 2.0;

        let entity = engine.world_mut().create_entity().with(physics);

        #[cfg(feature = "rendering")]
        let entity = entity
            .with(Position {
                x: physics.position_x - physics.radius,
                y: physics.position_y - physics.radius,
            })
            .with(Sprite {
                width: physics.radius * 2.0,
                height: physics.radius * 2.0,
                color: Color::new(1.0, 0.3, 0.3, 1.0),
            });

        match entity.build() {
            Ok(_) => {}
            Err(error) => {
                // Report the failure and abort the generation: the host keeps
                // the previously loaded module when project_init returns non-zero.
                error!(
                    target: pill_core::telemetry::telemetry_target::ECS,
                    error = %error,
                    "failed to build a ball entity; aborting this project generation"
                );
                return 1;
            }
        }
    }

    run_dummy_module_demo();

    // Report successful registration so the host keeps this generation.
    0
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ball_bounces_off_floor() {
        let mut state = initial_physics_state();
        state.position_y = FLOOR_Y - state.radius;
        state.velocity_y = 100.0;

        simulate_ball(&mut state);

        assert_eq!(state.position_y, FLOOR_Y - state.radius);
        assert!(state.velocity_y < 0.0);
    }

    #[test]
    fn inactive_ball_does_not_move() {
        let mut state = initial_physics_state();
        state.active = false;
        let before = state;

        simulate_ball(&mut state);

        assert_eq!(state.position_x, before.position_x);
        assert_eq!(state.position_y, before.position_y);
        assert_eq!(state.velocity_x, before.velocity_x);
        assert_eq!(state.velocity_y, before.velocity_y);
    }

    /// A weak floor bounce is restored so balls never settle on the floor.
    #[test]
    fn ball_never_rests_on_the_floor() {
        let mut state = initial_physics_state();
        state.position_y = FLOOR_Y - state.radius;
        state.velocity_y = 5.0;

        simulate_ball(&mut state);

        assert!(state.velocity_y <= -MINIMUM_BOUNCE_VELOCITY_Y);
    }
}
