//! Small generational arena used by the transferred renderer's GPU resources.
//!
//! # Responsibilities
//!
//! - Hand out `Copy` handles that name one slot each, so the renderer can pass
//!   them around while the map keeps owning the values.
//! - Validate every access against the version a handle was issued at, so a
//!   handle to a removed value fails instead of aliasing whatever refills its
//!   slot.
//!
//! # Design
//!
//! Slots carry the current version and handles carry the version they were
//! issued at; comparing the two is what turns a stale handle into a miss.
//! `SlotMap` stays generic over the key, so the five renderer handle types
//! share this one implementation.

// Standard library
use std::{marker::PhantomData, num::NonZeroU32};

/// Index and version that together identify one incarnation of a slot.
///
/// A handle carries the `KeyData` it was issued with, and the slot stores its
/// own version; a lookup only succeeds while the two match. Reusing a slot
/// bumps its version, so a handle from before the reuse stops validating
/// rather than naming its successor.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct KeyData {
    /// Position of the slot in the map's backing vector.
    pub index: u32,
    /// Version the slot must still carry for the handle to validate.
    pub version: NonZeroU32,
}

/// A typed handle for one entry of a [`SlotMap`].
///
/// Each implementation is a thin wrapper over a [`KeyData`], so handles stay
/// `Copy` and never borrow the value; the wrapper type records which slot map
/// the handle may be used with.
pub trait SlotKey: Copy + Eq {
    /// Builds a handle from a raw slot index and the version the slot must
    /// still carry for the handle to validate.
    ///
    /// Called where a handle is reconstructed outside the map's own insert -
    /// the draw path rebuilds one per queued item from its packed key - and
    /// where a fresh map seeds a placeholder handle to overwrite.
    fn new(index: u32, version: NonZeroU32) -> Self;

    /// Returns the raw [`KeyData`] the map validates the handle against.
    fn data(self) -> KeyData;
}

// Every renderer GPU resource handle is the same `KeyData` wrapper, differing
// only in name and in which slot map accepts it, so one macro stamps out the
// type, its accessors and its `SlotKey` impl. Five handle types come out of
// it: material, mesh, camera, texture and shader.
macro_rules! define_slot_key {
    ($name:ident) => {
        /// A typed handle for the slots of the map it was issued by.
        ///
        /// Generated by `define_slot_key!`; the wrapper type keeps handles
        /// from different maps apart.
        #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
        pub struct $name(KeyData);

        impl $name {
            /// Builds a handle from a raw slot index and the version the slot
            /// must still carry for the handle to validate.
            pub fn new(index: u32, version: NonZeroU32) -> Self {
                Self(KeyData { index, version })
            }

            /// Returns the raw [`KeyData`] the map validates the handle
            /// against.
            pub fn data(self) -> KeyData {
                self.0
            }
        }

        impl SlotKey for $name {
            fn new(index: u32, version: NonZeroU32) -> Self {
                Self::new(index, version)
            }

            fn data(self) -> KeyData {
                self.data()
            }
        }
    };
}

define_slot_key!(RendererMaterialHandle);
define_slot_key!(RendererMeshHandle);
define_slot_key!(RendererCameraHandle);
define_slot_key!(RendererTextureHandle);
define_slot_key!(RendererShaderHandle);

struct Slot<V> {
    version: NonZeroU32,
    value: Option<V>,
}

/// Generational slot arena that hands out typed [`SlotKey`] handles.
///
/// One map backs each GPU resource kind the renderer stores. Removal bumps the
/// slot's version, so replacing a resource can never make an old handle read
/// the new value; freed slots are reused before the slot vector grows.
pub struct SlotMap<K, V> {
    slots: Vec<Slot<V>>,
    free: Vec<u32>,
    marker: PhantomData<fn() -> K>,
}

impl<K: SlotKey, V> SlotMap<K, V> {
    /// Creates an empty map for key type `K`, with room for `capacity` values.
    ///
    /// The renderer fixes `K` per resource kind when it builds its storage;
    /// nothing in the arguments constrains it, which is why the key is named
    /// in the method itself.
    pub fn with_capacity_and_key(capacity: usize) -> Self {
        Self {
            slots: Vec::with_capacity(capacity),
            free: Vec::new(),
            marker: PhantomData,
        }
    }

    /// Inserts a value and returns the handle that names it.
    ///
    /// A freed slot is reused before the vector grows, keeping the version its
    /// removal left behind, so the returned handle never equals the one that
    /// freed the slot.
    pub fn insert(&mut self, value: V) -> K {
        if let Some(index) = self.free.pop() {
            let slot = &mut self.slots[index as usize];
            slot.value = Some(value);
            return K::new(index, slot.version);
        }
        let index = self.slots.len() as u32;
        let version = NonZeroU32::new(1).unwrap();
        self.slots.push(Slot {
            version,
            value: Some(value),
        });
        K::new(index, version)
    }

    /// Looks up the value a handle names, or `None` if the handle is stale.
    ///
    /// The slot's version must match the handle's, so a slot emptied or reused
    /// after the handle was issued reads as stale.
    pub fn get(&self, key: K) -> Option<&V> {
        let data = key.data();
        let slot = self.slots.get(data.index as usize)?;
        (slot.version == data.version)
            .then_some(slot.value.as_ref())
            .flatten()
    }

    /// Looks up the value a handle names for mutation.
    ///
    /// Validation is the same as [`get`](Self::get): a stale handle yields
    /// `None` instead of aliasing the value that inherited its slot.
    pub fn get_mut(&mut self, key: K) -> Option<&mut V> {
        let data = key.data();
        let slot = self.slots.get_mut(data.index as usize)?;
        (slot.version == data.version)
            .then_some(slot.value.as_mut())
            .flatten()
    }

    /// Take the value out of its slot, invalidating every handle to it.
    ///
    /// The slot is freed for reuse behind a bumped version, so a handle kept
    /// from before the removal can never name whatever refills it. At the
    /// version ceiling the slot is retired instead of wrapped - the same policy
    /// `AssetManager` applies to its generations - because a version that
    /// wrapped would validate handles issued before the last few removals.
    pub fn remove(&mut self, key: K) -> Option<V> {
        let data = key.data();
        let slot = self.slots.get_mut(data.index as usize)?;
        if slot.version != data.version {
            return None;
        }
        let value = slot.value.take()?;
        let next = slot.version.get().saturating_add(1);
        slot.version = NonZeroU32::new(next).unwrap();
        if next < u32::MAX {
            self.free.push(data.index);
        }
        Some(value)
    }
}
