//! How a compiled replacement reaches every running copy of a function.
//!
//! # Responsibilities
//!
//! - Resolve a function's address and signature inside a loaded patch image.
//! - Walk every image that may carry a copy: loaded artifacts, then the patches
//!   already in the process.
//! - Install, reset, or prologue-patch that function in each of them.
//!
//! # Design
//!
//! A crate linked into several artifacts is compiled into each of them, and a
//! generated patch links its own copy of whatever its body calls. A replacement
//! that reached only the crate's own DLL would leave every other copy running
//! the old code, so all three routes fan out across both kinds - which is why
//! they share one traversal ([`every_copy`]) rather than each walking their own.
//!
//! Leaving the patches out of that walk is what made a chain of hot functions
//! freeze at whatever the callee looked like when the caller was compiled.

// External crates
use libloading::{Library, Symbol};
use pill_core::debug;

// Current crate
use super::{PATCH_PLAIN_EXPORT, PATCH_RESOLVER_EXPORT};
use crate::native_library::NativeLibrary;

/// Ask a loaded patch for one function's address and signature hash.
pub(super) fn resolve_in(library: &Library, lookup_name: &str) -> Result<(usize, u64), String> {
    type ResolveFn = unsafe extern "C" fn(*const std::ffi::c_char, *mut u64) -> usize;

    // SAFETY: the export is generated by `pill_hot_resolver!` with exactly this
    // C ABI signature, and the borrow ends before the library is moved.
    let resolve: Symbol<ResolveFn> =
        unsafe { library.get(PATCH_RESOLVER_EXPORT) }.map_err(|_| {
            format!(
                "the patch does not export `{}`",
                String::from_utf8_lossy(PATCH_RESOLVER_EXPORT)
            )
        })?;

    let encoded = std::ffi::CString::new(lookup_name)
        .map_err(|_| "the function name contains a NUL byte".to_string())?;
    let mut signature_hash: u64 = 0;
    // SAFETY: a NUL-terminated name and a writable u64, as the export requires.
    let address = unsafe { resolve(encoded.as_ptr(), &mut signature_hash) };

    if address == 0 {
        return Err(format!("the patch does not define `{lookup_name}`"));
    }
    Ok((address, signature_hash))
}

/// Ask a loaded patch where its replacement for a plain function lives.
///
/// Returns the address to jump to and the signature text the patch compiled it
/// with, which every receiving artifact checks against its own before
/// accepting the replacement.
pub(super) fn resolve_plain_in(
    library: &Library,
    lookup_name: &str,
) -> Result<(usize, String), String> {
    type ResolvePlainFn =
        unsafe extern "C" fn(*const std::ffi::c_char, *mut *const u8, *mut usize) -> usize;

    // SAFETY: the export is generated by `pill_hot_resolver!` with exactly this
    // C ABI signature, and the borrow ends before the library is moved.
    let resolve: Symbol<ResolvePlainFn> =
        unsafe { library.get(PATCH_PLAIN_EXPORT) }.map_err(|_| {
            format!(
                "the patch does not export `{}`",
                String::from_utf8_lossy(PATCH_PLAIN_EXPORT)
            )
        })?;

    let encoded = std::ffi::CString::new(lookup_name)
        .map_err(|_| "the function name contains a NUL byte".to_string())?;
    let mut signature_pointer: *const u8 = std::ptr::null();
    let mut signature_length: usize = 0;
    // SAFETY: a NUL-terminated name and two writable slots, as the export
    // requires. On success it writes a pointer into the patch's own static
    // storage, which stays mapped because patches are never unloaded.
    let address = unsafe {
        resolve(
            encoded.as_ptr(),
            &mut signature_pointer,
            &mut signature_length,
        )
    };

    if address == 0 {
        return Err(format!("the patch does not define `{lookup_name}`"));
    }
    if signature_pointer.is_null() {
        return Err(format!(
            "the patch reported no signature for `{lookup_name}`"
        ));
    }
    // SAFETY: the export wrote a pointer and length describing a `&'static str`
    // inside the loaded patch, so the bytes are readable and valid UTF-8.
    let signature = unsafe { std::slice::from_raw_parts(signature_pointer, signature_length) };
    let signature = std::str::from_utf8(signature)
        .map_err(|_| "the patch reported a signature that is not UTF-8".to_string())?;
    Ok((address, signature.to_string()))
}

/// One loaded image that may carry a copy of the function being patched.
///
/// A crate linked into several artifacts is compiled into each of them, and a
/// generated patch links its own copy of whatever its body calls. Both kinds
/// therefore hold code that a replacement has to reach, and every fan-out below
/// walks both. The enum exists so that walk is written once: the two kinds
/// expose the same three operations with slightly different signatures, and
/// normalizing them here keeps the difference out of the callers.
enum PatchCopy<'a> {
    /// A module or project DLL the host loaded.
    Artifact(&'a NativeLibrary),
    /// A patch image compiled earlier in this session.
    Patch(&'a LoadedPatch),
}

impl PatchCopy<'_> {
    /// Point this copy's redirect slot at `address`.
    ///
    /// `Ok(false)` means the image does not link the crate at all, which is not
    /// a failure - it simply has nothing to redirect.
    fn install_plain_function(
        &self,
        qualified: &str,
        address: usize,
        signature: &str,
    ) -> Result<bool, String> {
        match self {
            Self::Artifact(artifact) => {
                artifact.install_plain_function(qualified, address, signature)
            }
            Self::Patch(patch) => patch.install_plain_function(qualified, address, signature),
        }
    }

    /// Empty this copy's redirect slot, restoring its own body.
    ///
    /// A patch reports a bare `bool` where an artifact reports `Result`; the
    /// bool is widened here so the traversal has one shape to handle.
    fn reset_plain_function(&self, qualified: &str) -> Result<bool, String> {
        match self {
            Self::Artifact(artifact) => artifact.reset_plain_function(qualified),
            Self::Patch(patch) => Ok(patch.reset_plain_function(qualified)),
        }
    }

    /// Where this copy's own compiled `qualified` lives, and the declaration it
    /// was built with.
    fn function_address(&self, qualified: &str) -> Option<(usize, String)> {
        match self {
            Self::Artifact(artifact) => artifact.function_address(qualified),
            Self::Patch(patch) => patch.function_address(qualified),
        }
    }

    /// How many of this copy's functions have a known extent, when it can say.
    ///
    /// Only an artifact carries the diagnostic export; a patch reports nothing,
    /// which is why the prologue refusal below only ever quotes artifacts.
    fn extent_coverage(&self) -> Option<(usize, usize)> {
        match self {
            Self::Artifact(artifact) => artifact.extent_coverage(),
            Self::Patch(_) => None,
        }
    }
}

/// Every image that could carry a copy of a function, labelled for diagnostics.
///
/// Artifacts first, then patches, which is the order every fan-out used before
/// they shared this walk. Leaving the patches out is what made a chain of hot
/// functions freeze at whatever the callee looked like when the caller was
/// compiled, so the two are deliberately not separable.
fn every_copy<'a>(
    targets: &'a [(&'a str, &'a NativeLibrary)],
    patches: &'a [LoadedPatch],
) -> impl Iterator<Item = (String, PatchCopy<'a>)> + 'a {
    targets
        .iter()
        .map(|(label, artifact)| ((*label).to_string(), PatchCopy::Artifact(artifact)))
        .chain(patches.iter().map(|patch| {
            (
                format!("{} patch gen {}", patch.function, patch.generation),
                PatchCopy::Patch(patch),
            )
        }))
}

/// Report a completed fan-out, or explain that it reached nothing.
///
/// Every fan-out shares this ending: reaching no copy at all is an error rather
/// than a silent success, because it means the replacement is not running
/// anywhere. The message differs by route, so it is supplied by the caller.
fn report_fan_out(
    reached: &[String],
    function: &str,
    nothing_reached: impl FnOnce() -> String,
    message: &'static str,
) -> Result<(), String> {
    if reached.is_empty() {
        return Err(nothing_reached());
    }
    debug!(
        target: pill_core::telemetry::telemetry_target::HOT_RELOAD,
        function,
        artifacts = reached.join(", ").as_str(),
        message
    );
    Ok(())
}

/// Offer one replacement to every loaded artifact, and report how many took it.
///
/// A crate linked into several artifacts is compiled into each of them, so the
/// project DLL runs its own embedded copy of a module it depends on. Installing
/// only into the module's own DLL would leave that copy running the old code,
/// which is exactly the situation that forces a cascading project reload today.
pub(super) fn install_everywhere(
    targets: &[(&str, &NativeLibrary)],
    patches: &[LoadedPatch],
    qualified: &str,
    address: usize,
    signature: &str,
) -> Result<usize, String> {
    let mut installed = Vec::new();
    for (label, copy) in every_copy(targets, patches) {
        match copy.install_plain_function(qualified, address, signature) {
            Ok(true) => installed.push(label),
            // This image simply does not link the crate.
            Ok(false) => {}
            // A refusal is reported rather than tolerated: leaving some
            // artifacts patched and others not would be worse than not
            // patching at all, and the caller falls back to a full reload.
            Err(detail) => return Err(format!("{label}: {detail}")),
        }
    }
    report_fan_out(
        &installed,
        qualified,
        || {
            format!(
                "no loaded artifact declares `{qualified}`; it may live in a crate \
                 nothing has loaded yet"
            )
        },
        "plain function redirected in every artifact that links it",
    )?;
    // How many copies were reached, which is what makes a fan-out visible in
    // the analytics line rather than assumed.
    Ok(installed.len())
}

/// Export a generated prologue patch carries so the host can find its new body.
///
/// One export, not a registry: a prologue patch replaces exactly one function,
/// so there is nothing to look up by name.
const PATCH_ADDRESS_EXPORT: &[u8] = b"pill_patch_address";

/// Address resolver a generated patch exports, distinct from an artifact's.
const PATCH_ADDRESS_RESOLVER: &[u8] = b"pill_patch_resolve_address";

/// Slot installer a generated patch exports.
const PATCH_INSTALL_RESOLVER: &[u8] = b"pill_patch_resolve_install";

/// Slot reset a generated patch exports.
const PATCH_RESET_RESOLVER: &[u8] = b"pill_patch_resolve_reset";

/// One previously loaded patch, offered as a target for later patches.
///
/// A patch links its own copy of everything its body calls, and those copies are
/// as stale as any other artifact's the moment a callee is patched. Without
/// this, a chain of hot functions freezes at whatever the callee looked like
/// when the caller's patch was compiled: patch `Spline::get_color_a`, then patch
/// `pill_dummy_color::get_color_a`, and the first patch keeps calling the old
/// second one.
pub(crate) struct LoadedPatch {
    /// The function this patch replaced, used as its label.
    pub function: String,
    /// Which generation it was.
    pub generation: u32,
    /// The loaded image. Never unloaded: a slot or a jump may point into it for
    /// the rest of the process, and nothing re-homes those addresses.
    pub library: Library,
}

impl LoadedPatch {
    /// Offer a replacement to this patch's own copy of one `#[pill_hot_fn]`.
    ///
    /// A patch links its own copy of whatever its body calls, slots included,
    /// and those slots start empty. Skipping them is what made a patched caller
    /// keep calling the compiled-in version of a callee patched afterwards.
    fn install_plain_function(
        &self,
        qualified: &str,
        address: usize,
        signature: &str,
    ) -> Result<bool, String> {
        type InstallFn =
            unsafe extern "C" fn(*const std::ffi::c_char, usize, *const std::ffi::c_char) -> u32;
        // SAFETY: generated by `pill_hot_resolver!` with this exact C ABI.
        let Ok(install) = (unsafe { self.library.get::<InstallFn>(PATCH_INSTALL_RESOLVER) }) else {
            return Ok(false);
        };
        let Ok(name) = std::ffi::CString::new(qualified) else {
            return Ok(false);
        };
        let Ok(signature) = std::ffi::CString::new(signature) else {
            return Ok(false);
        };
        // SAFETY: both strings are NUL-terminated and live until the call
        // returns, and `address` points into an image that is never unloaded.
        let status = unsafe { install(name.as_ptr(), address, signature.as_ptr()) };
        match status {
            0 => Ok(true),
            1 => Ok(false),
            _ => Err(format!(
                "`{qualified}` changed shape inside the {} patch",
                self.function
            )),
        }
    }

    /// Return this patch's copy of one `#[pill_hot_fn]` to its own body.
    fn reset_plain_function(&self, qualified: &str) -> bool {
        type ResetFn = unsafe extern "C" fn(*const std::ffi::c_char) -> u32;
        // SAFETY: generated by `pill_hot_resolver!` with this exact C ABI.
        let Ok(reset) = (unsafe { self.library.get::<ResetFn>(PATCH_RESET_RESOLVER) }) else {
            return false;
        };
        let Ok(name) = std::ffi::CString::new(qualified) else {
            return false;
        };
        // SAFETY: the string is NUL-terminated and lives until the call returns.
        unsafe { reset(name.as_ptr()) == 0 }
    }

    /// Address and recorded declaration of one function inside this patch.
    fn function_address(&self, qualified: &str) -> Option<(usize, String)> {
        type AddressFn =
            unsafe extern "C" fn(*const std::ffi::c_char, *mut *const u8, *mut usize) -> usize;
        // SAFETY: the export is generated by `pill_hot_resolver!` with exactly
        // this C ABI signature, and the borrow ends before the library moves.
        let resolve: Symbol<AddressFn> =
            unsafe { self.library.get(PATCH_ADDRESS_RESOLVER) }.ok()?;
        let name = std::ffi::CString::new(qualified).ok()?;
        let mut signature_pointer: *const u8 = std::ptr::null();
        let mut signature_length: usize = 0;
        // SAFETY: a NUL-terminated name and two writable slots, as the export
        // requires. A patch is never unloaded, so anything it reports stays
        // valid for the process lifetime.
        let address =
            unsafe { resolve(name.as_ptr(), &mut signature_pointer, &mut signature_length) };
        if address == 0 {
            return None;
        }
        let signature = if signature_pointer.is_null() {
            String::new()
        } else {
            // SAFETY: the export wrote a pointer and length describing a
            // `&'static str` inside the loaded patch.
            let bytes = unsafe { std::slice::from_raw_parts(signature_pointer, signature_length) };
            String::from_utf8_lossy(bytes).into_owned()
        };
        Some((address, signature))
    }
}

/// One artifact's copy of a prologue-patched function, and the bytes it had.
///
/// Saved so a rollback can put the function back exactly as the artifact was
/// built, which is the only way back for a mechanism that overwrites code in
/// place. Keyed by address rather than by artifact name because an artifact
/// that reloads gets a new image, and the old addresses must then be forgotten.
#[derive(Debug, Clone)]
pub(crate) struct PrologueRestore {
    /// Artifact the patched copy lives in, for diagnostics.
    pub artifact: String,
    /// Address of the function that was overwritten.
    pub address: usize,
    /// The bytes that were there before.
    pub original: Vec<u8>,
}

/// Ask a loaded prologue patch where its replacement body lives.
pub(super) fn resolve_patch_address(library: &Library) -> Result<usize, String> {
    type AddressFn = unsafe extern "C" fn() -> usize;
    // SAFETY: the export is generated by this module with exactly this C ABI
    // signature, and the borrow ends before the library is moved.
    let resolve: Symbol<AddressFn> =
        unsafe { library.get(PATCH_ADDRESS_EXPORT) }.map_err(|_| {
            format!(
                "the patch does not export `{}`",
                String::from_utf8_lossy(PATCH_ADDRESS_EXPORT)
            )
        })?;
    // SAFETY: the export takes no arguments and returns the address of a
    // function inside the patch image, which is never unloaded.
    let address = unsafe { resolve() };
    if address == 0 {
        return Err("the patch reported a null address".to_string());
    }
    Ok(address)
}

/// Redirect every loaded copy of one function by overwriting its prologue.
///
/// This is the macro-free route. Nothing in the running artifact was prepared
/// for the patch: the host asks each artifact for the function's address
/// through its build-script inventory and writes a jump over the first bytes.
///
/// The safety contract is the caller's: this must run at a frame boundary, on
/// the thread that runs the frame loop, with no system executing - which is
/// exactly where the fast path is invoked from.
pub(super) fn prologue_patch_everywhere(
    targets: &[(&str, &NativeLibrary)],
    patches: &[LoadedPatch],
    qualified: &str,
    replacement: usize,
    expected_signature: &str,
) -> Result<Vec<PrologueRestore>, String> {
    let mut restores: Vec<PrologueRestore> = Vec::new();
    for (label, copy) in every_copy(targets, patches) {
        let label = label.as_str();
        let Some((address, signature)) = copy.function_address(qualified) else {
            // This image simply does not link the crate.
            continue;
        };

        // The gate. Overwriting a function's first bytes can check nothing
        // about what it jumps to, so the shape has to be checked before the
        // write - and checked against what THIS artifact was built with, not
        // against another copy. Classification should already have refused a
        // changed signature; this is what catches it having been wrong.
        if !signature.is_empty() && signature != expected_signature {
            return Err(format!(
                "{label}: `{qualified}` was built as `{signature}` but the edit \
                 declares `{expected_signature}`; refusing to redirect callers \
                 compiled for the old shape"
            ));
        }
        // SAFETY: `address` came from the artifact's own inventory, so it names
        // a real function in a library the host keeps mapped; `replacement`
        // points into a patch image that is never unloaded. No thread is inside
        // the overwritten bytes, because this runs at the frame boundary on the
        // frame-loop thread with no system executing.
        match unsafe { pill_engine::hot_patch::patch_prologue(address, replacement) } {
            Ok(original) => restores.push(PrologueRestore {
                artifact: (*label).to_string(),
                address,
                original,
            }),
            Err(detail) => {
                // Say how widespread the cause is, so a refusal reads as a
                // diagnosis rather than a dead end. Only an artifact carries the
                // diagnostic export, so a patch contributes nothing here.
                let coverage = copy
                    .extent_coverage()
                    .map(|(known, total)| {
                        format!(
                            " ({known} of {total} functions in this artifact have a known length)"
                        )
                    })
                    .unwrap_or_default();
                // Undo whatever already landed, so a failure never leaves the
                // process half-patched.
                for restore in restores.iter().rev() {
                    // SAFETY: the same contract, with bytes this function saved
                    // moments ago from that exact address.
                    let _ = unsafe {
                        pill_engine::hot_patch::restore_prologue(restore.address, &restore.original)
                    };
                }
                return Err(format!("{label}: {detail}{coverage}"));
            }
        }
    }
    let reached: Vec<String> = restores
        .iter()
        .map(|restore| restore.artifact.clone())
        .collect();
    report_fan_out(
        &reached,
        qualified,
        || {
            format!(
                "no loaded artifact reports an address for `{qualified}`; its crate may not \
                 generate the function inventory"
            )
        },
        "prologue redirected in every artifact that links it",
    )?;
    Ok(restores)
}

/// Return one function to its own body in every artifact that declares it.
///
/// The counterpart of [`install_everywhere`] for a rollback to generation zero.
/// A plain function has one baseline per artifact, so each is asked to empty
/// its own slot rather than being handed an address belonging to another.
pub(super) fn reset_everywhere(
    targets: &[(&str, &NativeLibrary)],
    patches: &[LoadedPatch],
    qualified: &str,
) -> Result<(), String> {
    let mut restored = Vec::new();
    for (label, copy) in every_copy(targets, patches) {
        match copy.reset_plain_function(qualified) {
            Ok(true) => restored.push(label),
            Ok(false) => {}
            Err(detail) => return Err(format!("{label}: {detail}")),
        }
    }
    report_fan_out(
        &restored,
        qualified,
        || format!("no loaded artifact declares `{qualified}`"),
        "plain function restored to its original body in every artifact",
    )
}
